CREATE OR REPLACE VIEW CRT_KER_02_OUTBOUND AS
WITH
PARAMS AS (
  SELECT
    TRUE AS APPLY_RANGE,
    TO_TIMESTAMP_NTZ('2025-08-25 12:00:00') AS START_TS,
    TO_TIMESTAMP_NTZ('2025-08-26 00:00:00') AS END_TS
),
PREP_LINES AS (
  SELECT
    P1.PECDOD,
    P1.P1CACT,
    P1.P1NANO,
    P1.P1NODP,
    P1.P1CDPO,
    P1.P1NANP,
    P1.P1NPRE,
    MAX(P1.P1CPRP || P1.P1CQAL) AS GRADE,
    SUM(P1.P1QODP) AS QTY_ORDERED,
    MIN(
      CASE WHEN P1.P1JOCA > 0 THEN
        LPAD(P1.P1SSCA,2,'0')||LPAD(P1.P1ANCA,2,'0')||'-'||LPAD(P1.P1MOCA,2,'0')||'-'||LPAD(P1.P1JOCA,2,'0')
        ||' '||SUBSTR(LPAD(COALESCE(LC.LCHDCA,0)::VARCHAR,6,'0'),1,2)||':'||SUBSTR(LPAD(COALESCE(LC.LCHDCA,0)::VARCHAR,6,'0'),3,2)
        ||' '||P1.P1CDLA
      ELSE NULL END
    ) AS WAVE,
    MAX(CA.CAPRCA) AS PRODCAT,
    MAX(CASE WHEN P1.P1CART LIKE '7%' THEN 1 ELSE 0 END) AS FLAG_PACKAGING_JEWELRY_SUB,
    MAX(P1.HVR_CHANGE_TIME) AS LAST_UPDATE
  FROM MODELS.KERING_GLOBE.HLPRPLP P1
  JOIN MODELS.KERING_GLOBE.KBCARTP CA
    ON CA.CACACT = P1.P1CACT AND P1.P1CART = CA.CASKUC
  LEFT JOIN MODELS.KERING_GLOBE.HLLANCP LC
    ON LC.LCCDPO=P1.P1CDPO AND LC.LCSSCA=P1.P1SSCA AND LC.LCANCA=P1.P1ANCA
   AND LC.LCMOCA=P1.P1MOCA AND LC.LCJOCA=P1.P1JOCA AND LC.LCCDLA=P1.P1CDLA
  WHERE P1.P1CACT='100'
    AND P1.P1CDPO='001'
    AND (
      (SELECT APPLY_RANGE FROM PARAMS) = FALSE
      OR (P1.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS)
          AND P1.HVR_CHANGE_TIME <  (SELECT END_TS   FROM PARAMS))
    )
  GROUP BY P1.PECDOD, P1.P1CACT, P1.P1NANO, P1.P1NODP, P1.P1CDPO, P1.P1NANP, P1.P1NPRE
),
PE AS (
  SELECT PE.*, CO.Commenti
  FROM MODELS.KERING_GLOBE.HLPRENP PE
  LEFT JOIN (
    SELECT c.CONCOM, LISTAGG(c.COTXTC, ' | ') WITHIN GROUP (ORDER BY c.CONLCO) AS Commenti
    FROM MODELS.KERING_GLOBE.HLCOMMP c
    JOIN (
      SELECT DISTINCT PE2.PENCOM
      FROM MODELS.KERING_GLOBE.HLPRENP PE2
      WHERE PE2.PECACT='100' AND PE2.PECDPO='001'
        AND (
          (SELECT APPLY_RANGE FROM PARAMS) = FALSE
          OR (PE2.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS)
              AND PE2.HVR_CHANGE_TIME <  (SELECT END_TS   FROM PARAMS))
        )
    ) used ON used.PENCOM = c.CONCOM
    GROUP BY c.CONCOM
  ) CO ON PE.PENCOM = CO.CONCOM
  WHERE PE.PECACT='100'
    AND PE.PECDPO='001'
    AND (
      (SELECT APPLY_RANGE FROM PARAMS) = FALSE
      OR (PE.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS)
          AND PE.HVR_CHANGE_TIME <  (SELECT END_TS   FROM PARAMS))
    )
),
HU AS (
  SELECT HU.HUCDPO, HU.HUDNUM, HU.HUPORD, MAX(HU.HUDMAJ) AS TK35HEURE, MAX(HU.HVR_CHANGE_TIME) AS LAST_UPDATE
  FROM MODELS.KERING_GLOBE.KB35HUP HU
  WHERE HU.HUCDPO='001'
    AND (
      (SELECT APPLY_RANGE FROM PARAMS) = FALSE
      OR (HU.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS)
          AND HU.HVR_CHANGE_TIME <  (SELECT END_TS   FROM PARAMS))
    )
  GROUP BY HU.HUCDPO, HU.HUDNUM, HU.HUPORD
),
PREP_LINES_QTY AS (
  SELECT P1.P1CDPO, P1.P1CACT, P1.P1NANP, P1.P1NPRE,
         SUM(LG.LGQLPG) AS QTY_PACK,
         SUM(CASE WHEN EM.EMC1EM='DMS' THEN LG.LGQLPG ELSE 0 END) AS QTY_DMS2,
         COUNT(DISTINCT GE.GENCOL) AS QTY_COL,
         COUNT(DISTINCT CASE WHEN SU.SUTSCG='1' THEN GE.GENCOL END) AS QTY_COL_LOAD,
         SUM(CASE WHEN SU.SUTSCG='1' THEN LG.LGQLPG ELSE 0 END) AS QTY_PIE_LOAD,
         MAX(COALESCE(GE.HVR_CHANGE_TIME, LG.HVR_CHANGE_TIME, SU.HVR_CHANGE_TIME, EM.HVR_CHANGE_TIME)) AS LAST_UPDATE
  FROM MODELS.KERING_GLOBE.HLPRPLP P1
  JOIN MODELS.KERING_GLOBE.HLLPRGP LG
    ON LG.LGCDPO=P1.P1CDPO AND LG.LGCACT=P1.P1CACT AND LG.LGNANN=P1.P1NANN AND LG.LGNLPR=P1.P1NLPR
  JOIN MODELS.KERING_GLOBE.HLGEINP GE
    ON GE.GENGEI=LG.LGNGEI AND LG.LGCDPO=GE.GECDPO AND LG.LGCACT=GE.GECACT AND GE.GENCOL <> ' '
  JOIN MODELS.KERING_GLOBE.HLSUPPP SU
    ON SU.SUCDPO=LG.LGCDPO AND SU.SUNSUP=GE.GENSUP
  JOIN MODELS.KERING_GLOBE.HLEMPLP EM
    ON SU.SUCDPO=EM.EMCDPO AND SU.SUNEMP=EM.EMNEMP
  WHERE (
    (SELECT APPLY_RANGE FROM PARAMS) = FALSE
    OR (
      P1.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS) AND P1.HVR_CHANGE_TIME < (SELECT END_TS FROM PARAMS)
      AND LG.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS) AND LG.HVR_CHANGE_TIME < (SELECT END_TS FROM PARAMS)
      AND GE.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS) AND GE.HVR_CHANGE_TIME < (SELECT END_TS FROM PARAMS)
      AND SU.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS) AND SU.HVR_CHANGE_TIME < (SELECT END_TS FROM PARAMS)
      AND EM.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS) AND EM.HVR_CHANGE_TIME < (SELECT END_TS FROM PARAMS)
    )
  )
  GROUP BY P1.P1CDPO, P1.P1CACT, P1.P1NANP, P1.P1NPRE
),
DMS_SUB AS (
  SELECT P1D.P1CACT, P1D.P1CDPO, P1D.P1NANP, P1D.P1NPRE, SUM(P1D.P1QODP) AS QTY_DMS
  FROM MODELS.KERING_GLOBE.HLPRPLP P1D
  JOIN MODELS.KERING_GLOBE.HLARVLP ARV
    ON P1D.P1CACT=ARV.VLCACT AND P1D.P1CART=ARV.VLCART AND ARV.VLCVLA='03'
  WHERE ARV.VLCFPR IN ('DMS')
    AND (
      (SELECT APPLY_RANGE FROM PARAMS) = FALSE
      OR (P1D.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS)
          AND P1D.HVR_CHANGE_TIME <  (SELECT END_TS   FROM PARAMS))
    )
  GROUP BY P1D.P1CACT, P1D.P1CDPO, P1D.P1NANP, P1D.P1NPRE
),
GS AS (
  SELECT GS.GSCDPO, GS.GSCACT, GS.GSNAPP, GS.GSNPRE,
         COUNT(DISTINCT GS.GSNCOL) AS QTY_COL_EXP,
         SUM(GS.GSQGEI) AS QTY_PIE_EXP,
         MAX(GS.HVR_CHANGE_TIME) AS LAST_UPDATE
  FROM MODELS.KERING_GLOBE.HLPRPLP P1
  JOIN MODELS.KERING_GLOBE.HLGESOP GS
    ON GS.GSCACT=P1.P1CACT AND GS.GSCDPO=P1.P1CDPO AND GS.GSNALI=P1.P1NANN AND GS.GSNLPR=P1.P1NLPR
  WHERE P1.P1CACT='100' AND P1.P1CDPO='001'
    AND (
      (SELECT APPLY_RANGE FROM PARAMS) = FALSE
      OR (
        P1.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS) AND P1.HVR_CHANGE_TIME < (SELECT END_TS FROM PARAMS)
        AND GS.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS) AND GS.HVR_CHANGE_TIME < (SELECT END_TS FROM PARAMS)
      )
    )
  GROUP BY GS.GSCDPO, GS.GSCACT, GS.GSNAPP, GS.GSNPRE
),
CO AS (
  SELECT DISTINCT CO.CORCDE
  FROM MODELS.KERING_GLOBE.KBDORDP OR_
  JOIN MODELS.KERING_GLOBE.KBMCLPP CO
    ON CO.COCDPO = OR_.ORCDPO AND CO.COCACT = OR_.ORCACT AND CO.COSTSE = OR_.ORORID
  WHERE OR_.ORCDPO='001' AND OR_.ORCACT='100'
),
SG1 AS (
  SELECT SUBSTR(SG.SGSRID,1,6) AS CGCOD,
         SUBSTR(SG.SGSRID,7,2) AS CGSIE,
         SUBSTR(SG.SGSRID,9,2) AS CGANN,
         SUBSTR(SG.SGSRID,11,2) AS CGMOI,
         SUBSTR(SG.SGSRID,13,2) AS CGJOU,
         MAX(SG.HVR_CHANGE_TIME) AS LAST_UPDATE
  FROM MODELS.KERING_GLOBE.KBDSSLP SG
  WHERE SG.SGCDPO='001' AND SG.SGCACT='100' AND SUBSTR(SG.SGSRID,9,1) <> '_'
    AND (
      (SELECT APPLY_RANGE FROM PARAMS) = FALSE
      OR (SG.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS)
          AND SG.HVR_CHANGE_TIME <  (SELECT END_TS   FROM PARAMS))
    )
  GROUP BY SUBSTR(SG.SGSRID,1,6),SUBSTR(SG.SGSRID,7,2),SUBSTR(SG.SGSRID,9,2),SUBSTR(SG.SGSRID,11,2),SUBSTR(SG.SGSRID,13,2)
),
SG2 AS (
  SELECT SUBSTR(SG.SGSRID,10,6) AS CGCOD,
         SUBSTR(SG.SGSRID,1,2)  AS CGSIE,
         SUBSTR(SG.SGSRID,3,2)  AS CGANN,
         SUBSTR(SG.SGSRID,5,2)  AS CGMOI,
         SUBSTR(SG.SGSRID,7,2)  AS CGJOU,
         MAX(SG.HVR_CHANGE_TIME) AS LAST_UPDATE
  FROM MODELS.KERING_GLOBE.KBDSSLP SG
  WHERE SG.SGCDPO='001' AND SG.SGCACT='100' AND SUBSTR(SG.SGSRID,9,1) = '_'
    AND (
      (SELECT APPLY_RANGE FROM PARAMS) = FALSE
      OR (SG.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS)
          AND SG.HVR_CHANGE_TIME <  (SELECT END_TS   FROM PARAMS))
    )
  GROUP BY SUBSTR(SG.SGSRID,10,6),SUBSTR(SG.SGSRID,1,2),SUBSTR(SG.SGSRID,3,2),SUBSTR(SG.SGSRID,5,2),SUBSTR(SG.SGSRID,7,2)
),
YMX AS (
  SELECT
    TD.TDTREFB,
    MAX(YMA.MO_ARRIVAL_DATE)   AS MO_ARRIVAL_DATE,
    MAX(YMB.MO_BAY_DATE)       AS MO_BAY_DATE,
    MAX(YMD.MO_DEPARTURE_DATE) AS MO_DEPARTURE_DATE
  FROM TIEADRSLOTTASK TD
  LEFT JOIN (
    SELECT YM1.IDSITE, YM1.IDDEPOT, YM1.MOSTATE, YM1.MOAPPOINTMENT,
           MIN(YM1.MOARRIVALDATE) AS MO_ARRIVAL_DATE,
           MAX(YM1.MOLICENCEPLATE1) AS MOLICENCEPLATE1,
           TS.TSLID
    FROM HISTORYMOVEMENT YM1
    JOIN TIEADRSLOT TS ON YM1.MOAPPOINTMENT = TS.TSLNUM
    WHERE YM1.IDSITE='1' AND YM1.IDDEPOT='4' AND YM1.MOSTATE=20
    GROUP BY YM1.IDSITE, YM1.IDDEPOT, YM1.MOSTATE, YM1.MOAPPOINTMENT, TS.TSLID
  ) YMA ON YMA.TSLID = TD.TDTTSLID
  LEFT JOIN (
    SELECT YM2.IDSITE, YM2.IDDEPOT, YM2.MOSTATE, YM2.MOAPPOINTMENT,
           MIN(YM2.HYTIMESTAMP) AS MO_BAY_DATE,
           MIN(D.DONAME) AS DOCK,
           TS.TSLID
    FROM HISTORYMOVEMENT YM2
    JOIN DOCK D ON D.IDDOCK = YM2.IDDOCK
    JOIN TIEADRSLOT TS ON YM2.MOAPPOINTMENT = TS.TSLNUM
    WHERE YM2.IDSITE='1' AND YM2.IDDEPOT='4' AND YM2.MOSTATE=60 AND YM2.IDSTATUS=3
    GROUP BY YM2.IDSITE, YM2.IDDEPOT, YM2.MOSTATE, YM2.MOAPPOINTMENT, TS.TSLID
  ) YMB ON YMB.TSLID = TD.TDTTSLID
  LEFT JOIN (
    SELECT YM4.IDSITE, YM4.IDDEPOT, YM4.MOSTATE, YM4.MOAPPOINTMENT,
           MIN(YM4.HYTIMESTAMP) AS MO_DEPARTURE_DATE,
           MIN(D.DONAME) AS DOCK,
           TS.TSLID
    FROM HISTORYMOVEMENT YM4
    JOIN DOCK D ON D.IDDOCK = YM4.IDDOCK
    JOIN TIEADRSLOT TS ON YM4.MOAPPOINTMENT = TS.TSLNUM
    WHERE YM4.IDSITE='1' AND YM4.IDDEPOT='4' AND YM4.MOSTATE=60 AND YM4.IDSTATUS=11
    GROUP BY YM4.IDSITE, YM4.IDDEPOT, YM4.MOSTATE, YM4.MOAPPOINTMENT, TS.TSLID
  ) YMBE ON YMBE.TSLID = TD.TDTTSLID
  LEFT JOIN (
    SELECT YM3.IDSITE, YM3.IDDEPOT, YM3.MOSTATE, YM3.MOAPPOINTMENT,
           MIN(YM3.MODEPARTUREDATE) AS MO_DEPARTURE_DATE,
           TS.TSLID
    FROM HISTORYMOVEMENT YM3
    JOIN TIEADRSLOT TS ON YM3.MOAPPOINTMENT = TS.TSLNUM
    WHERE YM3.IDSITE='1' AND YM3.IDDEPOT='4' AND YM3.MOSTATE=99
    GROUP BY YM3.IDSITE, YM3.IDDEPOT, YM3.MOSTATE, YM3.MOAPPOINTMENT, TS.TSLID
  ) YMD ON YMD.TSLID = TD.TDTTSLID
  GROUP BY TD.TDTREFB
),
BASE AS (
  SELECT
    MD5_BINARY('B' || OE.OENANN || OE.OENODP || PE.PECACT || PE.PECDPO || PE.PERODP || PE.PENANN || PE.PENPRE) AS PK_FACT_OUTBOUND,
    COALESCE(MOTHER.SHDCOR, CHILD.SHDCOR)::DATE AS INTEGRATION_DATE,
    TO_CHAR(COALESCE(MOTHER.SHDCOR, CHILD.SHDCOR), 'HH24:MI') AS INTEGRATION_TIME,
    'Reflex WEB B' AS ENVIRONMENT,
    'B' AS BUILDING,
    SUBSTR(PREP_LINES.GRADE,1,3) AS REFLEX_CLIENT,
    PE.PECDES AS REFLEX_DESTINATION,
    CAST(NULL AS DATE) AS WAVING_DATE,
    CASE WHEN PREP_LINES.WAVE IS NOT NULL THEN SUBSTR(PREP_LINES.WAVE,18,3) ELSE NULL END AS WAVING_CODE,
    CASE WHEN CO.CORCDE IS NULL THEN NULL ELSE 'SENT' END AS ORDER_INSERT_UPDATE,
    CASE WHEN COALESCE(SG1.CGCOD, SG2.CGCOD) IS NULL THEN NULL ELSE 'DONE' END AS SHIPPING_REQUEST,
    CASE WHEN MOTHER.SHCDOR IS NULL THEN CHILD.SHCDOR ELSE MOTHER.SHCDOR END AS BRAND,
    CASE WHEN MOTHER.SHRDOR IS NULL THEN CHILD.SHRDOR ELSE MOTHER.SHRDOR END AS SAP_ORDERID,
    OE.OECDES AS CUSTOMER_CODE,
    CASE WHEN MOTHER.SHPAYD IS NULL THEN CHILD.SHPAYD ELSE MOTHER.SHPAYD END AS COUNTRY,
    MOTHER.SHCTRP AS SAP_CARRIER,
    CG.CGCTRP AS REFLEX_CARRIER,
    TP.TPLTRP AS CARRIER_NAME,
    SUBSTR(PREP_LINES.GRADE,1,3) AS OWNER,
    SUBSTR(PREP_LINES.GRADE,4,3) AS QUALITY,
    CASE WHEN CHILD.SHCACT IS NULL THEN LPAD(PE.PENANN,2,'0') || '/' || LPAD(PE.PENPRE,9,'0')
         ELSE LPAD(CHILD.SHNANN,2,'0') || '/' || LPAD(CHILD.SHNPRP,9,'0') END AS PREPARATION_NUMBER,
    (CASE WHEN CHILD.SHCACT IS NULL THEN MOTHER.SHDDEL ELSE CHILD.SHDDEL END)::DATE AS DELIVERY_DATE,
    TRY_TO_DATE(
      LPAD(((COALESCE(PE.PESSCA,0)::INT)*100 + COALESCE(PE.PEANCA,0)::INT)::VARCHAR, 4, '0') || '-' ||
      LPAD(COALESCE(PE.PEMOCA,0)::VARCHAR, 2, '0') || '-' ||
      LPAD(COALESCE(PE.PEJOCA,0)::VARCHAR, 2, '0'),
      'YYYY-MM-DD'
    ) AS LOAD_DATE,
    PE.PECCHA AS LOAD_CODE,
    CASE WHEN U9.U9NARV > 0 THEN LPAD(U9.U9NARV,2,'0') || '/' || LPAD(U9.U9NRDV,9,'0') ELSE NULL END AS RDV,
    CG.CGNPLC AS PLATE_NUMBER,
    CAST(NULL AS TIMESTAMP) AS TRUCK_DEPARTURE,
    CASE WHEN HU.HUCDPO IS NOT NULL THEN HU.TK35HEURE ELSE NULL END AS TK35_TRANSMISSION,
    CASE WHEN CHILD.SHCACT IS NULL THEN
           CASE WHEN COALESCE(MOTHER.SHTTKP,0)=0 THEN NULL ELSE MOTHER.SHDTKP END
         ELSE
           CASE WHEN COALESCE(CHILD.SHTTKP,0)=0 THEN NULL ELSE CHILD.SHDTKP END
    END AS TK05_PACKED_DATE,
    CASE WHEN CHILD.SHCACT IS NULL THEN
           CASE WHEN COALESCE(MOTHER.SHTTKS,0)=0 THEN NULL ELSE MOTHER.SHDTKS END
         ELSE
           CASE WHEN COALESCE(CHILD.SHTTKS,0)=0 THEN NULL ELSE CHILD.SHDTKS END
    END AS TK05_SHIPPED_DATE,
    CASE WHEN CHILD.SHCACT IS NULL THEN MOTHER.SHCINV ELSE CHILD.SHCINV END AS INVOICE_CODE,
    YMX.MO_ARRIVAL_DATE   AS TRUCK_GATE_ARRIVAL,
    YMX.MO_BAY_DATE       AS TRUCK_BAY_ARRIVAL,
    YMX.MO_DEPARTURE_DATE AS EVENT_490,
    CASE WHEN CHILD.SHCACT IS NULL THEN
           CASE WHEN COALESCE(MOTHER.SHDINV::DATE, DATE '0001-01-01') = DATE '0001-01-01' THEN NULL ELSE MOTHER.SHDINV END
         ELSE
           CASE WHEN COALESCE(CHILD.SHDINV::DATE,  DATE '0001-01-01') = DATE '0001-01-01' THEN NULL ELSE CHILD.SHDINV END
    END AS INVOICE_DATE,
    CASE WHEN PE.PETSOP='1' AND PE.PETSOL='1' THEN 0 ELSE PREP_LINES.QTY_ORDERED END AS QUANTITY_ORDERED,
    CASE WHEN PE.PETSOP='1' THEN PE.PETBPV ELSE PE.PETBPV END AS QUANTITY_PICKED,
    CASE WHEN PE.PETSOP='1' THEN PE.PETBPV ELSE COALESCE(PREP_LINES_QTY.QTY_PACK,0) END AS QUANTITY_PACKED,
    CASE WHEN PE.PET1PP=0 OR (PE.PETSOL='1' AND PE.PET1PP>0) THEN 0
         WHEN DMS_SUB.QTY_DMS IS NULL THEN 0 ELSE DMS_SUB.QTY_DMS END AS QUANTITY_DMS,
    CASE WHEN PE.PETSOP='1' THEN COALESCE(GS.QTY_COL_EXP,0) ELSE COALESCE(PREP_LINES_QTY.QTY_COL_LOAD,0) END AS PARCELS_LOADED,
    CASE WHEN PE.PETSOP='1' THEN COALESCE(GS.QTY_PIE_EXP,0) ELSE COALESCE(PREP_LINES_QTY.QTY_PIE_LOAD,0) END AS PIECES_LOADED,
    (CASE WHEN PE.PETSOP='1' THEN COALESCE(GS.QTY_COL_EXP,0) ELSE COALESCE(PREP_LINES_QTY.QTY_COL,0) END)::VARCHAR AS CARTONS,
    CASE WHEN PE.PET1PP=0 OR (PE.PETSOL='1' AND PE.PET1PP>0) THEN 'CANCEL' ELSE NULL END AS TK05_CANCEL_FLAG,
    CASE
      WHEN CHILD.SHCACT IS NULL THEN
        CASE WHEN COALESCE(MOTHER.SHTTKP,0)=0 AND (PE.PET1PP=0 OR (PE.PETSOL='1' AND PE.PET1PP>0)) THEN NULL
             ELSE MOTHER.SHDTKP END
      ELSE
        CASE WHEN COALESCE(CHILD.SHTTKP,0)=0 AND (PE.PET1PP=0 OR (PE.PETSOL='1' AND PE.PET1PP>0)) THEN NULL
             ELSE CASE WHEN COALESCE(CHILD.SHTTKP,0)=0 THEN NULL ELSE CHILD.SHDTKP END END
    END AS TK05_CANCEL_DATE,
    CASE
      WHEN MOTHER.SHDIPA IS NOT NULL AND MOTHER.SHDIPA::DATE <> DATE '0001-01-01' THEN MOTHER.SHDIPA
      WHEN CHILD.SHDIPA  IS NOT NULL AND CHILD.SHDIPA::DATE  <> DATE '0001-01-01' THEN CHILD.SHDIPA
      ELSE NULL
    END AS INITIAL_PLANNED_PACKING_DATE,
    CASE
      WHEN MOTHER.SHDIPA IS NOT NULL AND MOTHER.SHDIPA::DATE <> DATE '0001-01-01' THEN MOTHER.SHDIPA
      WHEN CHILD.SHDIPA  IS NOT NULL AND CHILD.SHDIPA::DATE  <> DATE '0001-01-01' THEN CHILD.SHDIPA
      ELSE NULL
    END AS INITIAL_PLANNED_PACKING_TIME,
    CASE
      WHEN MOTHER.SHDPPA IS NOT NULL AND MOTHER.SHDPPA::DATE <> DATE '0001-01-01' THEN MOTHER.SHDPPA::DATE
      WHEN CHILD.SHDPPA  IS NOT NULL AND CHILD.SHDPPA::DATE  <> DATE '0001-01-01' THEN CHILD.SHDPPA::DATE
      ELSE NULL
    END AS PLANNED_PACKING_DATE,
    CASE
      WHEN MOTHER.SHDPPA IS NOT NULL AND MOTHER.SHDPPA::DATE <> DATE '0001-01-01' THEN TO_CHAR(MOTHER.SHDPPA,'HH24:MI')
      WHEN CHILD.SHDPPA  IS NOT NULL AND CHILD.SHDPPA::DATE  <> DATE '0001-01-01' THEN TO_CHAR(CHILD.SHDPPA,'HH24:MI')
      ELSE NULL
    END AS PLANNED_PACKING_TIME,
    CASE
      WHEN MOTHER.SHDILP IS NOT NULL AND MOTHER.SHDILP::DATE <> DATE '0001-01-01' THEN MOTHER.SHDILP::DATE
      WHEN CHILD.SHDILP  IS NOT NULL AND CHILD.SHDILP::DATE  <> DATE '0001-01-01' THEN CHILD.SHDILP::DATE
      ELSE NULL
    END AS INITIAL_LATEST_PLANNED_PACKING_DATE,
    CASE
      WHEN MOTHER.SHDILP IS NOT NULL AND MOTHER.SHDILP::DATE <> DATE '0001-01-01' THEN TO_CHAR(MOTHER.SHDILP,'HH24:MI')
      WHEN CHILD.SHDILP  IS NOT NULL AND CHILD.SHDILP::DATE  <> DATE '0001-01-01' THEN TO_CHAR(CHILD.SHDILP,'HH24:MI')
      ELSE NULL
    END AS INITIAL_LATEST_PLANNED_PACKING_TIME,
    CASE
      WHEN MOTHER.SHDLPA IS NOT NULL AND MOTHER.SHDLPA::DATE <> DATE '0001-01-01' THEN MOTHER.SHDLPA::DATE
      WHEN CHILD.SHDLPA  IS NOT NULL AND CHILD.SHDLPA::DATE  <> DATE '0001-01-01' THEN CHILD.SHDLPA::DATE
      ELSE NULL
    END AS LATEST_PLANNED_PACKING_DATE,
    CASE
      WHEN MOTHER.SHDLPA IS NOT NULL AND MOTHER.SHDLPA::DATE <> DATE '0001-01-01' THEN TO_CHAR(MOTHER.SHDLPA,'HH24:MI')
      WHEN CHILD.SHDLPA  IS NOT NULL AND CHILD.SHDLPA::DATE  <> DATE '0001-01-01' THEN TO_CHAR(CHILD.SHDLPA,'HH24:MI')
      ELSE NULL
    END AS LATEST_PLANNED_PACKING_TIME,
    CASE
      WHEN MOTHER.SHDIPU IS NOT NULL AND MOTHER.SHDIPU::DATE <> DATE '0001-01-01' THEN MOTHER.SHDIPU::DATE
      WHEN CHILD.SHDIPU  IS NOT NULL AND CHILD.SHDIPU::DATE  <> DATE '0001-01-01' THEN CHILD.SHDIPU::DATE
      ELSE NULL
    END AS INITIAL_PICKUP_DATE,
    CASE
      WHEN MOTHER.SHDIPU IS NOT NULL AND MOTHER.SHDIPU::DATE <> DATE '0001-01-01' THEN TO_CHAR(MOTHER.SHDIPU,'HH24:MI')
      WHEN CHILD.SHDIPU  IS NOT NULL AND CHILD.SHDIPU::DATE  <> DATE '0001-01-01' THEN TO_CHAR(CHILD.SHDIPU,'HH24:MI')
      ELSE NULL
    END AS INITIAL_PICKUP_TIME,
    CASE
      WHEN MOTHER.SHDPUP IS NOT NULL AND MOTHER.SHDPUP::DATE <> DATE '0001-01-01' THEN MOTHER.SHDPUP::DATE
      WHEN CHILD.SHDPUP  IS NOT NULL AND CHILD.SHDPUP::DATE  <> DATE '0001-01-01' THEN CHILD.SHDPUP::DATE
      ELSE NULL
    END AS PICKUP_DATE,
    '00:00' AS PICKUP_TIME,
    PE.PECMOP AS FLOW,
    CASE
      WHEN PE.PECMOP='C1'  THEN 'CA'
      WHEN PE.PECMOP='EDO' THEN 'Export Doc (GB Malpensa)'
      WHEN PE.PECMOP='ESD' THEN 'Export Doc & Stop&Go'
      WHEN PE.PECMOP='EXP' THEN 'Export Doc (Internal)'
      WHEN PE.PECMOP='FCA' THEN 'FCA/EXW'
      WHEN PE.PECMOP='FES' THEN 'EXW - Export Doc & Stop'
      WHEN PE.PECMOP='FEX' THEN 'EXW - Export Doc'
      WHEN PE.PECMOP='FOG' THEN 'FCA + OK to Ship'
      WHEN PE.PECMOP='FOS' THEN 'FCA + OK to Ship & Stop&G'
      WHEN PE.PECMOP='FSG' THEN 'FCA + Stop&Go'
      WHEN PE.PECMOP='HAL' THEN 'Hallmarking'
      WHEN PE.PECMOP='MTM' THEN 'Make to Order, Make to Measure'
      WHEN PE.PECMOP='TK9' THEN NULL
      WHEN PE.PECMOP='VAN' THEN 'Vanilla'
      WHEN PE.PECMOP='VIN' THEN 'Invoice Required'
      WHEN PE.PECMOP='VOK' THEN 'OK to Ship'
      WHEN PE.PECMOP='VOS' THEN 'Stop & GO & OK to Ship'
      WHEN PE.PECMOP='VSI' THEN 'Invoice Required & Stop'
      WHEN PE.PECMOP='VST' THEN 'Vanilla Stop & GO'
      WHEN PE.PECMOP='WAN' THEN 'do not delete'
      WHEN PE.PECMOP='WTP' THEN 'do not delete'
      ELSE NULL
    END AS FLOW_DESCRIPTION,
    CASE WHEN MOTHER.SHTHZM IS NULL THEN CHILD.SHTHZM ELSE MOTHER.SHTHZM END AS FLAG_HAZMAT,
    CASE WHEN MOTHER.SHTFSC IS NULL THEN CHILD.SHTFSC ELSE MOTHER.SHTFSC END AS FLAG_FSC,
    CASE WHEN MOTHER.SHTJEW IS NULL THEN CHILD.SHTJEW ELSE MOTHER.SHTJEW END AS FLAG_JEWELLERY,
    PREP_LINES.FLAG_PACKAGING_JEWELRY_SUB AS FLAG_PACKAGING_JEWELLERY,
    CASE WHEN MOTHER.SHTHMK IS NULL THEN CHILD.SHTHMK ELSE MOTHER.SHTHMK END AS FLAG_HALMARKING,
    CASE WHEN MOTHER.SHSHMK IS NULL THEN CHILD.SHSHMK ELSE MOTHER.SHSHMK END AS HALMARKING_STATUS,
    CASE WHEN MOTHER.SHTCIT IS NULL THEN CHILD.SHTCIT ELSE MOTHER.SHTCIT END AS FLAG_IMPACT_CITES,
    CASE WHEN MOTHER.SHSCIT IS NULL THEN CHILD.SHSCIT ELSE MOTHER.SHSCIT END AS CITES_STATUS,
    CASE WHEN VAS.VAS_CODE IS NULL THEN '0' ELSE '1' END AS VAS_FLAG,
    VAS.VAS_CODE AS VAS_CODE,
    VAS.VAS_CLUSTER AS VAS_CLUSTER,
    MOTHER.SHMOTR AS SAP_MEAN_OF_TRANSPORT,
    CG.CGCTMT AS REFLEX_MEAN_OF_TRANSPORT,
    CASE WHEN MOTHER.SHCLUS IS NULL THEN CHILD.SHCLUS ELSE MOTHER.SHCLUS END AS CLUSTER,
    CASE WHEN MOTHER.SHCHAN IS NULL THEN CHILD.SHCHAN ELSE MOTHER.SHCHAN END AS CHANNEL,
    CASE WHEN MOTHER.SHTCEE IS NULL THEN (CASE WHEN CHILD.SHTCEE='1' THEN 'CEE' ELSE 'EXTRA' END)
         ELSE (CASE WHEN MOTHER.SHTCEE='1' THEN 'CEE' ELSE 'EXTRA' END) END AS FLAG_CEE,
    CASE WHEN MOTHER.SHTTSP IS NULL THEN CHILD.SHTTSP ELSE MOTHER.SHTTSP END AS FLAG_IS_TO_SHIP,
    CASE WHEN MOTHER.SHTSTP IS NULL THEN CHILD.SHTSTP ELSE MOTHER.SHTSTP END AS FLAG_IS_STOP,
    CASE WHEN PE.PET1PP=0 OR (PE.PETSOL='1' AND PE.PET1PP>0) THEN '1' ELSE '0' END AS FLAG_IS_CANCELLED,
    CASE WHEN MOTHER.SHTMAA IS NULL THEN CHILD.SHTMAA ELSE MOTHER.SHTMAA END AS FLAG_MAX_ATTENTION,
    CASE WHEN MOTHER.SHNPRI IS NULL THEN CHILD.SHNPRI ELSE MOTHER.SHNPRI END AS PRIORITY,
    CASE WHEN MOTHER.SHDOCT IS NULL THEN CHILD.SHDOCT ELSE MOTHER.SHDOCT END AS DOCUMENT_TYPE,
    CASE WHEN MOTHER.SHFLOT IS NULL THEN CHILD.SHFLOT ELSE MOTHER.SHFLOT END AS FLOW_TYPE,
    CASE WHEN MOTHER.SHLROU IS NULL THEN CHILD.SHLROU ELSE MOTHER.SHLROU END AS ROUTE,
    CASE WHEN MOTHER.SHLSHC IS NULL THEN CHILD.SHLSHC ELSE MOTHER.SHLSHC END AS SHIPPING_CONDITION,
    CASE WHEN MOTHER.SHCDEG IS NULL THEN CHILD.SHCDEG ELSE MOTHER.SHCDEG END AS CODE_DELIVERY_GROUP,
    CASE WHEN CHILD.SHLDEB IS NULL THEN MOTHER.SHLDEB ELSE CHILD.SHLDEB END AS DELIVERY_BLOCK,
    CASE WHEN CHILD.SHCACT IS NULL THEN MOTHER.SHLSHB ELSE CHILD.SHLSHB END AS SHIPMENT_BLOCKED,
    CASE WHEN MOTHER.SHTREO IS NULL THEN CHILD.SHTREO ELSE MOTHER.SHTREO END AS FLAG_IS_RELEASE_OD,
    CASE WHEN CHILD.SHCACT IS NULL THEN MOTHER.SHREXT ELSE CHILD.SHREXT END AS EXTERNAL_ID,
    CASE WHEN CHILD.SHCACT IS NULL THEN MOTHER.SHREX5 ELSE CHILD.SHREX5 END AS ORDER_ID_SENT_IN_TK05,
    CASE WHEN CHILD.SHTURG IS NULL THEN MOTHER.SHTURG ELSE CHILD.SHTURG END AS FLAG_URGENT,
    CASE WHEN CHILD.SHTCUT IS NULL THEN MOTHER.SHTCUT ELSE CHILD.SHTCUT END AS FLAG_CUT_OFF,
    CASE WHEN CHILD.SHTDMM IS NULL THEN MOTHER.SHTDMM ELSE CHILD.SHTDMM END AS FLAG_DMM_RECALCULATION,
    CASE WHEN MOTHER.SHDCPU IS NULL THEN (CASE WHEN CHILD.SHDCPU::DATE = DATE '0001-01-01' THEN NULL ELSE CHILD.SHDCPU END)
         ELSE (CASE WHEN MOTHER.SHDCPU::DATE = DATE '0001-01-01' THEN NULL ELSE MOTHER.SHDCPU END) END AS DMM_PICKUP,
    CASE WHEN MOTHER.SHDCPA IS NULL THEN (CASE WHEN CHILD.SHDCPA::DATE = DATE '0001-01-01' THEN NULL ELSE CHILD.SHDCPA END)
         ELSE (CASE WHEN MOTHER.SHDCPA::DATE = DATE '0001-01-01' THEN NULL ELSE MOTHER.SHDCPA END) END AS DMM_PACKING,
    PE.PETOPD AS FLAG_ORDER_DESACTIVATED,
    GREATEST(
      COALESCE(OE.HVR_CHANGE_TIME,           TO_TIMESTAMP_NTZ('1900-01-01 00:00:01')),
      COALESCE(PREP_LINES.LAST_UPDATE,       TO_TIMESTAMP_NTZ('1900-01-01 00:00:01')),
      COALESCE(MOTHER.HVR_CHANGE_TIME,       TO_TIMESTAMP_NTZ('1900-01-01 00:00:01')),
      COALESCE(CHILD.HVR_CHANGE_TIME,        TO_TIMESTAMP_NTZ('1900-01-01 00:00:01')),
      COALESCE(CG.HVR_CHANGE_TIME,           TO_TIMESTAMP_NTZ('1900-01-01 00:00:01')),
      COALESCE(U9.HVR_CHANGE_TIME,           TO_TIMESTAMP_NTZ('1900-01-01 00:00:01')),
      COALESCE(U6.HVR_CHANGE_TIME,           TO_TIMESTAMP_NTZ('1900-01-01 00:00:01')),
      COALESCE(HU.LAST_UPDATE,               TO_TIMESTAMP_NTZ('1900-01-01 00:00:01')),
      COALESCE(GS.LAST_UPDATE,               TO_TIMESTAMP_NTZ('1900-01-01 00:00:01'))
    ) AS CHANGE_TS,
    '0' AS ISDELETED,
    PREP_LINES.PRODCAT AS PRODUCT_CATEGORY,
    COALESCE(PE.Commenti, NULL) AS COMMENTI
  FROM MODELS.KERING_GLOBE.HLODPEP OE
  JOIN PREP_LINES
    ON PREP_LINES.PECDOD = OE.OECDPO
   AND PREP_LINES.P1CACT = OE.OECACT
   AND PREP_LINES.P1NANO = OE.OENANN
   AND PREP_LINES.P1NODP = OE.OENODP
  JOIN PE
    ON PREP_LINES.P1CDPO = PE.PECDPO
   AND PREP_LINES.P1CACT = PE.PECACT
   AND PE.PENANN         = PREP_LINES.P1NANP
   AND PE.PENPRE         = PREP_LINES.P1NPRE
  LEFT JOIN MODELS.KERING_GLOBE.KBSHIPP MOTHER
    ON MOTHER.SHCDEP = OE.OECDPO AND MOTHER.SHCACT = OE.OECACT
   AND MOTHER.SHCDOR = OE.OECDDO AND MOTHER.SHRDOR = OE.OERODP AND MOTHER.SHNANN = 0
  LEFT JOIN MODELS.KERING_GLOBE.KBSHIPP CHILD
    ON CHILD.SHCDEP = PE.PECDPO AND CHILD.SHCACT = PE.PECACT
   AND CHILD.SHNANN = PE.PENANN AND CHILD.SHNPRP = PE.PENPRE
  LEFT JOIN MODELS.KERING_GLOBE.HLCHARP CG
    ON CG.CGCDPO = PE.PECDPO AND PE.PESSCA = CG.CGSSCA AND PE.PEANCA = CG.CGANCA
   AND PE.PEMOCA = CG.CGMOCA AND PE.PEJOCA = CG.CGJOCA AND PE.PECCHA = CG.CGCCHA
  LEFT JOIN MODELS.KERING_GLOBE.HLRDVCP U9
    ON U9.U9CDPO = CG.CGCDPO AND U9.U9SSCA = CG.CGSSCA AND U9.U9ANCA = CG.CGANCA
   AND U9.U9MOCA = CG.CGMOCA AND U9.U9JOCA = CG.CGJOCA AND U9.U9CCHA = CG.CGCCHA
  LEFT JOIN MODELS.KERING_GLOBE.HLRDVTP U6
    ON U9.U9CDPO = U6.U6CDPO AND U9.U9NARV = U6.U6NARV AND U9.U9NRDV = U6.U6NRDV
  LEFT JOIN MODELS.KERING_GLOBE.HLTRSPP TP
    ON CG.CGCTRP = TP.TPCTRP
  LEFT JOIN HU
    ON PE.PECDPO = HU.HUCDPO AND PE.PERODP = HU.HUDNUM
   AND HU.HUPORD = LPAD(PE.PENANN,2,'0') || LPAD(PE.PENPRE,9,'0')
  LEFT JOIN PREP_LINES_QTY
    ON PREP_LINES_QTY.P1CDPO = PE.PECDPO AND PREP_LINES_QTY.P1CACT = PE.PECACT
   AND PREP_LINES_QTY.P1NANP = PE.PENANN  AND PREP_LINES_QTY.P1NPRE = PE.PENPRE
  LEFT JOIN DMS_SUB
    ON DMS_SUB.P1CDPO = PE.PECDPO AND DMS_SUB.P1CACT = PE.PECACT
   AND DMS_SUB.P1NANP = PE.PENANN  AND DMS_SUB.P1NPRE = PE.PENPRE
  LEFT JOIN GS
    ON GS.GSCDPO = PE.PECDPO AND GS.GSCACT = PE.PECACT
   AND GS.GSNAPP = PE.PENANN AND GS.GSNPRE = PE.PENPRE
  LEFT JOIN FACT_KER_02_OUTBOUND_VAS VAS
    ON PE.PECDPO = VAS.P1CDPO AND PE.PECACT = VAS.P1CACT
   AND PE.PENANN = VAS.P1NANP AND PE.PENPRE = VAS.P1NPRE
  LEFT JOIN CO  ON CO.CORCDE = PE.PERODP
  LEFT JOIN SG1 ON SG1.CGCOD = PE.PECCHA AND SG1.CGSIE = PE.PESSCA AND SG1.CGANN = PE.PEANCA AND SG1.CGMOI = PE.PEMOCA AND SG1.CGJOU = PE.PEJOCA
  LEFT JOIN SG2 ON SG2.CGCOD = PE.PECCHA AND SG2.CGSIE = PE.PESSCA AND SG2.CGANN = PE.PEANCA AND SG2.CGMOI = PE.PEMOCA AND SG2.CGJOU = PE.PEJOCA
  LEFT JOIN YMX ON YMX.TDTREFB = U6.U6LRDV
  WHERE OE.OECDPO = '001'
    AND OE.OECACT = '100'
    AND (
      (SELECT APPLY_RANGE FROM PARAMS) = FALSE
      OR (OE.HVR_CHANGE_TIME >= (SELECT START_TS FROM PARAMS)
          AND OE.HVR_CHANGE_TIME <  (SELECT END_TS   FROM PARAMS))
    )
)
SELECT
  PK_FACT_OUTBOUND,
  INTEGRATION_DATE, INTEGRATION_TIME,
  ENVIRONMENT, BUILDING,
  REFLEX_CLIENT, REFLEX_DESTINATION, WAVING_DATE, WAVING_CODE,
  ORDER_INSERT_UPDATE, SHIPPING_REQUEST,
  BRAND, SAP_ORDERID, CUSTOMER_CODE, COUNTRY,
  SAP_CARRIER, REFLEX_CARRIER, CARRIER_NAME,
  OWNER, QUALITY, PREPARATION_NUMBER,
  DELIVERY_DATE, LOAD_DATE, LOAD_CODE, RDV, PLATE_NUMBER, TRUCK_DEPARTURE,
  TK35_TRANSMISSION, TK05_PACKED_DATE, TK05_SHIPPED_DATE, INVOICE_CODE,
  TRUCK_GATE_ARRIVAL, TRUCK_BAY_ARRIVAL, EVENT_490, INVOICE_DATE,
  QUANTITY_ORDERED, QUANTITY_PICKED, QUANTITY_PACKED, QUANTITY_DMS,
  PARCELS_LOADED, PIECES_LOADED, CARTONS,
  TK05_CANCEL_FLAG, TK05_CANCEL_DATE,
  INITIAL_PLANNED_PACKING_DATE, INITIAL_PLANNED_PACKING_TIME,
  PLANNED_PACKING_DATE, PLANNED_PACKING_TIME,
  INITIAL_LATEST_PLANNED_PACKING_DATE, INITIAL_LATEST_PLANNED_PACKING_TIME,
  LATEST_PLANNED_PACKING_DATE, LATEST_PLANNED_PACKING_TIME,
  INITIAL_PICKUP_DATE, INITIAL_PICKUP_TIME, PICKUP_DATE, PICKUP_TIME,
  FLOW, FLOW_DESCRIPTION,
  FLAG_HAZMAT, FLAG_FSC, FLAG_JEWELLERY, FLAG_PACKAGING_JEWELLERY,
  FLAG_HALMARKING, HALMARKING_STATUS,
  FLAG_IMPACT_CITES, CITES_STATUS,
  VAS_FLAG, VAS_CODE, VAS_CLUSTER,
  SAP_MEAN_OF_TRANSPORT, REFLEX_MEAN_OF_TRANSPORT,
  CLUSTER, CHANNEL, FLAG_CEE, FLAG_IS_TO_SHIP, FLAG_IS_STOP, FLAG_IS_CANCELLED,
  FLAG_MAX_ATTENTION, PRIORITY, DOCUMENT_TYPE, FLOW_TYPE, ROUTE,
  SHIPPING_CONDITION, CODE_DELIVERY_GROUP, DELIVERY_BLOCK, SHIPMENT_BLOCKED,
  FLAG_IS_RELEASE_OD, EXTERNAL_ID, ORDER_ID_SENT_IN_TK05,
  FLAG_URGENT, FLAG_CUT_OFF, FLAG_DMM_RECALCULATION,
  DMM_PICKUP, DMM_PACKING,
  FLAG_ORDER_DESACTIVATED,
  CHANGE_TS AS UPDATED_DATE,
  ISDELETED,
  PRODUCT_CATEGORY,
  COMMENTI
FROM BASE;

CREATE OR REPLACE PROCEDURE SP_KER_02_OUTBOUND_LOAD(SAFETY_HOURS INTEGER DEFAULT 4)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO FACT_KER_02_OUTBOUND t
  USING (
    SELECT *
    FROM   CRT_KER_02_OUTBOUND
    WHERE  UPDATED_DATE >= DATEADD(
             hour, - :SAFETY_HOURS,
             COALESCE(
               (SELECT LAST_UPDATE FROM OBJECT_RUN WHERE "OBJECT" = '02_OUTBOUND'),
               TO_TIMESTAMP_NTZ('1900-01-01 00:00:00')
             )
           )
  ) s
  ON (t.PK_FACT_OUTBOUND = s.PK_FACT_OUTBOUND)

  WHEN MATCHED THEN UPDATE SET
      INTEGRATION_DATE              = s.INTEGRATION_DATE,
      INTEGRATION_TIME              = s.INTEGRATION_TIME,
      ENVIRONMENT                   = s.ENVIRONMENT,
      BUILDING                      = s.BUILDING,
      REFLEX_CLIENT                 = s.REFLEX_CLIENT,
      REFLEX_DESTINATION            = s.REFLEX_DESTINATION,
      WAVING_DATE                   = s.WAVING_DATE,
      WAVING_CODE                   = s.WAVING_CODE,
      ORDER_INSERT_UPDATE           = s.ORDER_INSERT_UPDATE,
      SHIPPING_REQUEST              = s.SHIPPING_REQUEST,
      BRAND                         = s.BRAND,
      SAP_ORDERID                   = s.SAP_ORDERID,
      CUSTOMER_CODE                 = s.CUSTOMER_CODE,
      COUNTRY                       = s.COUNTRY,
      SAP_CARRIER                   = s.SAP_CARRIER,
      REFLEX_CARRIER                = s.REFLEX_CARRIER,
      CARRIER_NAME                  = s.CARRIER_NAME,
      OWNER                         = s.OWNER,
      QUALITY                       = s.QUALITY,
      PREPARATION_NUMBER            = s.PREPARATION_NUMBER,
      DELIVERY_DATE                 = s.DELIVERY_DATE,
      LOAD_DATE                     = s.LOAD_DATE,
      LOAD_CODE                     = s.LOAD_CODE,
      RDV                           = s.RDV,
      PLATE_NUMBER                  = s.PLATE_NUMBER,
      TRUCK_DEPARTURE               = s.TRUCK_DEPARTURE,
      TK35_TRANSMISSION             = s.TK35_TRANSMISSION,
      TK05_PACKED_DATE              = s.TK05_PACKED_DATE,
      TK05_SHIPPED_DATE             = s.TK05_SHIPPED_DATE,
      INVOICE_CODE                  = s.INVOICE_CODE,
      TRUCK_GATE_ARRIVAL            = s.TRUCK_GATE_ARRIVAL,
      TRUCK_BAY_ARRIVAL             = s.TRUCK_BAY_ARRIVAL,
      EVENT_490                     = s.EVENT_490,
      INVOICE_DATE                  = s.INVOICE_DATE,
      QUANTITY_ORDERED              = s.QUANTITY_ORDERED,
      QUANTITY_PICKED               = s.QUANTITY_PICKED,
      QUANTITY_PACKED               = s.QUANTITY_PACKED,
      QUANTITY_DMS                  = s.QUANTITY_DMS,
      PARCELS_LOADED                = s.PARCELS_LOADED,
      PIECES_LOADED                 = s.PIECES_LOADED,
      CARTONS                       = s.CARTONS,
      TK05_CANCEL_FLAG              = s.TK05_CANCEL_FLAG,
      TK05_CANCEL_DATE              = s.TK05_CANCEL_DATE,
      INITIAL_PLANNED_PACKING_DATE  = s.INITIAL_PLANNED_PACKING_DATE,
      INITIAL_PLANNED_PACKING_TIME  = s.INITIAL_PLANNED_PACKING_TIME,
      PLANNED_PACKING_DATE          = s.PLANNED_PACKING_DATE,
      PLANNED_PACKING_TIME          = s.PLANNED_PACKING_TIME,
      INITIAL_LATEST_PLANNED_PACKING_DATE = s.INITIAL_LATEST_PLANNED_PACKING_DATE,
      INITIAL_LATEST_PLANNED_PACKING_TIME = s.INITIAL_LATEST_PLANNED_PACKING_TIME,
      LATEST_PLANNED_PACKING_DATE   = s.LATEST_PLANNED_PACKING_DATE,
      LATEST_PLANNED_PACKING_TIME   = s.LATEST_PLANNED_PACKING_TIME,
      INITIAL_PICKUP_DATE           = s.INITIAL_PICKUP_DATE,
      INITIAL_PICKUP_TIME           = s.INITIAL_PICKUP_TIME,
      PICKUP_DATE                   = s.PICKUP_DATE,
      PICKUP_TIME                   = s.PICKUP_TIME,
      FLOW                          = s.FLOW,
      FLOW_DESCRIPTION              = s.FLOW_DESCRIPTION,
      FLAG_HAZMAT                   = s.FLAG_HAZMAT,
      FLAG_FSC                      = s.FLAG_FSC,
      FLAG_JEWELLERY                = s.FLAG_JEWELLERY,
      FLAG_PACKAGING_JEWELLERY      = s.FLAG_PACKAGING_JEWELLERY,
      FLAG_HALMARKING               = s.FLAG_HALMARKING,
      HALMARKING_STATUS             = s.HALMARKING_STATUS,
      VAS_FLAG                      = s.VAS_FLAG,
      VAS_CODE                      = s.VAS_CODE,
      VAS_CLUSTER                   = s.VAS_CLUSTER,
      SAP_MEAN_OF_TRANSPORT         = s.SAP_MEAN_OF_TRANSPORT,
      REFLEX_MEAN_OF_TRANSPORT      = s.REFLEX_MEAN_OF_TRANSPORT,
      CLUSTER                       = s.CLUSTER,
      CHANNEL                       = s.CHANNEL,
      FLAG_CEE                      = s.FLAG_CEE,
      FLAG_IS_TO_SHIP               = s.FLAG_IS_TO_SHIP,
      FLAG_IS_STOP                  = s.FLAG_IS_STOP,
      FLAG_IS_CANCELLED             = s.FLAG_IS_CANCELLED,
      FLAG_MAX_ATTENTION            = s.FLAG_MAX_ATTENTION,
      PRIORITY                      = s.PRIORITY,
      DOCUMENT_TYPE                 = s.DOCUMENT_TYPE,
      FLOW_TYPE                     = s.FLOW_TYPE,
      ROUTE                         = s.ROUTE,
      SHIPPING_CONDITION            = s.SHIPPING_CONDITION,
      CODE_DELIVERY_GROUP           = s.CODE_DELIVERY_GROUP,
      DELIVERY_BLOCK                = s.DELIVERY_BLOCK,
      SHIPMENT_BLOCKED              = s.SHIPMENT_BLOCKED,
      FLAG_IS_RELEASE_OD            = s.FLAG_IS_RELEASE_OD,
      EXTERNAL_ID                   = s.EXTERNAL_ID,
      ORDER_ID_SENT_IN_TK05         = s.ORDER_ID_SENT_IN_TK05,
      FLAG_URGENT                   = s.FLAG_URGENT,
      FLAG_CUT_OFF                  = s.FLAG_CUT_OFF,
      FLAG_DMM_RECALCULATION        = s.FLAG_DMM_RECALCULATION,
      DMM_PICKUP                    = s.DMM_PICKUP,
      DMM_PACKING                   = s.DMM_PACKING,
      UPDATED_DATE                  = s.UPDATED_DATE,
      ISDELETED                     = s.ISDELETED,
      PRODUCT_CATEGORY              = s.PRODUCT_CATEGORY,
      COMMENTI                      = s.COMMENTI

  WHEN NOT MATCHED THEN INSERT (
      PK_FACT_OUTBOUND, INTEGRATION_DATE, INTEGRATION_TIME, ENVIRONMENT, BUILDING,
      REFLEX_CLIENT, REFLEX_DESTINATION, WAVING_DATE, WAVING_CODE,
      ORDER_INSERT_UPDATE, SHIPPING_REQUEST, BRAND, SAP_ORDERID, CUSTOMER_CODE, COUNTRY,
      SAP_CARRIER, REFLEX_CARRIER, CARRIER_NAME, OWNER, QUALITY, PREPARATION_NUMBER,
      DELIVERY_DATE, LOAD_DATE, LOAD_CODE, RDV, PLATE_NUMBER, TRUCK_DEPARTURE,
      TK35_TRANSMISSION, TK05_PACKED_DATE, TK05_SHIPPED_DATE, INVOICE_CODE,
      TRUCK_GATE_ARRIVAL, TRUCK_BAY_ARRIVAL, EVENT_490, INVOICE_DATE,
      QUANTITY_ORDERED, QUANTITY_PICKED, QUANTITY_PACKED, QUANTITY_DMS,
      PARCELS_LOADED, PIECES_LOADED, CARTONS, TK05_CANCEL_FLAG, TK05_CANCEL_DATE,
      INITIAL_PLANNED_PACKING_DATE, INITIAL_PLANNED_PACKING_TIME,
      PLANNED_PACKING_DATE, PLANNED_PACKING_TIME,
      INITIAL_LATEST_PLANNED_PACKING_DATE, INITIAL_LATEST_PLANNED_PACKING_TIME,
      LATEST_PLANNED_PACKING_DATE, LATEST_PLANNED_PACKING_TIME,
      INITIAL_PICKUP_DATE, INITIAL_PICKUP_TIME, PICKUP_DATE, PICKUP_TIME,
      FLOW, FLOW_DESCRIPTION, FLAG_HAZMAT, FLAG_FSC, FLAG_JEWELLERY, FLAG_PACKAGING_JEWELLERY,
      FLAG_HALMARKING, HALMARKING_STATUS, VAS_FLAG, VAS_CODE, VAS_CLUSTER,
      SAP_MEAN_OF_TRANSPORT, REFLEX_MEAN_OF_TRANSPORT, CLUSTER, CHANNEL, FLAG_CEE,
      FLAG_IS_TO_SHIP, FLAG_IS_STOP, FLAG_IS_CANCELLED, FLAG_MAX_ATTENTION, PRIORITY,
      DOCUMENT_TYPE, FLOW_TYPE, ROUTE, SHIPPING_CONDITION, CODE_DELIVERY_GROUP, DELIVERY_BLOCK,
      SHIPMENT_BLOCKED, FLAG_IS_RELEASE_OD, EXTERNAL_ID, ORDER_ID_SENT_IN_TK05,
      FLAG_URGENT, FLAG_CUT_OFF, FLAG_DMM_RECALCULATION, DMM_PICKUP, DMM_PACKING,
      UPDATED_DATE, ISDELETED, PRODUCT_CATEGORY, COMMENTI
  )
  VALUES (
      s.PK_FACT_OUTBOUND, s.INTEGRATION_DATE, s.INTEGRATION_TIME, s.ENVIRONMENT, s.BUILDING,
      s.REFLEX_CLIENT, s.REFLEX_DESTINATION, s.WAVING_DATE, s.WAVING_CODE,
      s.ORDER_INSERT_UPDATE, s.SHIPPING_REQUEST, s.BRAND, s.SAP_ORDERID, s.CUSTOMER_CODE, s.COUNTRY,
      s.SAP_CARRIER, s.REFLEX_CARRIER, s.CARRIER_NAME, s.OWNER, s.QUALITY, s.PREPARATION_NUMBER,
      s.DELIVERY_DATE, s.LOAD_DATE, s.LOAD_CODE, s.RDV, s.PLATE_NUMBER, s.TRUCK_DEPARTURE,
      s.TK35_TRANSMISSION, s.TK05_PACKED_DATE, s.TK05_SHIPPED_DATE, s.INVOICE_CODE,
      s.TRUCK_GATE_ARRIVAL, s.TRUCK_BAY_ARRIVAL, s.EVENT_490, s.INVOICE_DATE,
      s.QUANTITY_ORDERED, s.QUANTITY_PICKED, s.QUANTITY_PACKED, s.QUANTITY_DMS,
      s.PARCELS_LOADED, s.PIECES_LOADED, s.CARTONS, s.TK05_CANCEL_FLAG, s.TK05_CANCEL_DATE,
      s.INITIAL_PLANNED_PACKING_DATE, s.INITIAL_PLANNED_PACKING_TIME,
      s.PLANNED_PACKING_DATE, s.PLANNED_PACKING_TIME,
      s.INITIAL_LATEST_PLANNED_PACKING_DATE, s.INITIAL_LATEST_PLANNED_PACKING_TIME,
      s.LATEST_PLANNED_PACKING_DATE, s.LATEST_PLANNED_PACKING_TIME,
      s.INITIAL_PICKUP_DATE, s.INITIAL_PICKUP_TIME, s.PICKUP_DATE, s.PICKUP_TIME,
      s.FLOW, s.FLOW_DESCRIPTION, s.FLAG_HAZMAT, s.FLAG_FSC, s.FLAG_JEWELLERY, s.FLAG_PACKAGING_JEWELLERY,
      s.FLAG_HALMARKING, s.HALMARKING_STATUS, s.VAS_FLAG, s.VAS_CODE, s.VAS_CLUSTER,
      s.SAP_MEAN_OF_TRANSPORT, s.REFLEX_MEAN_OF_TRANSPORT, s.CLUSTER, s.CHANNEL, s.FLAG_CEE,
      s.FLAG_IS_TO_SHIP, s.FLAG_IS_STOP, s.FLAG_IS_CANCELLED, s.FLAG_MAX_ATTENTION, s.PRIORITY,
      s.DOCUMENT_TYPE, s.FLOW_TYPE, s.ROUTE, s.SHIPPING_CONDITION, s.CODE_DELIVERY_GROUP, s.DELIVERY_BLOCK,
      s.SHIPMENT_BLOCKED, s.FLAG_IS_RELEASE_OD, s.EXTERNAL_ID, s.ORDER_ID_SENT_IN_TK05,
      s.FLAG_URGENT, s.FLAG_CUT_OFF, s.FLAG_DMM_RECALCULATION, s.DMM_PICKUP, s.DMM_PACKING,
      s.UPDATED_DATE, s.ISDELETED, s.PRODUCT_CATEGORY, s.COMMENTI
  );

  MERGE INTO OBJECT_RUN d
  USING (
    SELECT '02_OUTBOUND' AS OBJECT,
           MAX(UPDATED_DATE) AS LAST_UPDATE
    FROM   CRT_KER_02_OUTBOUND
    WHERE  UPDATED_DATE >= DATEADD(
             hour, - :SAFETY_HOURS,
             COALESCE(
               (SELECT LAST_UPDATE FROM OBJECT_RUN WHERE "OBJECT" = '02_OUTBOUND'),
               TO_TIMESTAMP_NTZ('1900-01-01 00:00:00')
             )
           )
  ) s
  ON d."OBJECT" = s.OBJECT
  WHEN MATCHED THEN UPDATE
    SET d.LAST_UPDATE = GREATEST(COALESCE(d.LAST_UPDATE, s.LAST_UPDATE), s.LAST_UPDATE)
  WHEN NOT MATCHED THEN INSERT ("OBJECT", LAST_UPDATE)
    VALUES (s.OBJECT, s.LAST_UPDATE);

  RETURN 'SP_KER_02_OUTBOUND_LOAD completed';
END;
$$;

