

CREATE OR REPLACE VIEW CRT_KER_01_INBOUND (
  "PK_FACT_INBOUND","ENVIRONMENT","QUALITY","UDM","SKU","INBOUND_REFERENCE","ASN",
  "FORECAST_QUANTITY","ACTUAL_QUANTITY","EAN","MODEL","PART","COLOUR","SIZE","DROP",
  "PRODUCT_CATEGORY","PRODUCT_SUBCATEGORY","TRUCK_PLATE","BUILDING","DOCK",
  "TRUCK_GATE_ARRIVAL","TRUCK_BAY_ARRIVAL","TRUCK_BAY_DEPARTURE","TRUCK_GATE_DEPARTURE",
  "UDM_RECEIVING","UDM_POSITIONING","APPOINTMENT_DATE","UPDATED_DATE","ISDELETED"
) AS
-- Optimized CTE Structure (KER)
WITH
/* Chunk 05: params — optional dev/test gates */
params AS (
  SELECT
    CAST(1 AS INTEGER) AS MAX_DAYS_BACK,           -- e.g., 3
    CAST('8136678664' AS VARCHAR) AS FILTER_SKU,              -- e.g., 'SKU123'
    CAST('0307596418' AS VARCHAR) AS FILTER_INBOUND_REFERENCE,-- e.g., '0181254821'
    CAST('0185981938' AS VARCHAR) AS FILTER_ASN,              -- e.g., 'ASN123'
    CAST(NULL AS VARCHAR) AS FILTER_DOCK              -- e.g., 'GATE-1'
),
/* Chunk 10: base_time_gate — derive cutoff timestamp */
base_time_gate AS (
  SELECT CASE
           WHEN (SELECT MAX_DAYS_BACK FROM params) IS NULL
             THEN TIMESTAMP '1900-01-01 00:00:00'
           ELSE DATEADD('day', - (SELECT MAX_DAYS_BACK FROM params), CURRENT_TIMESTAMP())
         END AS cutoff_ts
),
/* Chunk 20: source_select — original logic wrapped */
source_select AS (
  SELECT 
    MD5('B' || '-' || COALESCE(YY.DEPOT, 'NA') || '-' || COALESCE(YY.ACTIVITY, 'NA') || '/' || COALESCE(YY.ITEM, 'NA') || '-' || COALESCE(YY.GRADE, 'NA') || '-' || COALESCE(YY.SUPPORT, 'NA') || '-' || COALESCE(YY.INBOUNDREF, 'NA')) AS "PK_FACT_INBOUND",
    'Reflex WEB B' AS "ENVIRONMENT",
    YY.GRADE AS "QUALITY",
    YY.SUPPORT AS "UDM",
    YY.ITEM AS "SKU",
    YY.INBOUNDREF AS "INBOUND_REFERENCE",
    YY.ASN AS "ASN",
    YY.QTY_EXPECT AS "FORECAST_QUANTITY",
    YY.QTY_CONFIRM AS "ACTUAL_QUANTITY",
    VI2.VICIVL AS "EAN",
    CA.CALMOD AS "MODEL",
    CA.CAPART AS "PART",
    CA.CACOLC AS "COLOUR",
    CA.CASIZC AS "SIZE",
    CA.CADROP AS "DROP",
    CA.CAPRCA AS "PRODUCT_CATEGORY",
    CA.CAPRFA AS "PRODUCT_SUBCATEGORY",
    YY.Lplate AS "TRUCK_PLATE",
    'B' AS "BUILDING",
    YY.DOCK AS "DOCK",
    CASE WHEN YY.Dat_Gate       = TIMESTAMP '1900-01-01 00:00:01' THEN NULL ELSE YY.Dat_Gate       END AS "TRUCK_GATE_ARRIVAL",
    CASE WHEN YY.Dat_Dock_in    = TIMESTAMP '1900-01-01 00:00:01' THEN NULL ELSE YY.Dat_Dock_in    END AS "TRUCK_BAY_ARRIVAL",
    CASE WHEN YY.Dat_Dock_out   = TIMESTAMP '1900-01-01 00:00:01' THEN NULL ELSE YY.Dat_Dock_out   END AS "TRUCK_BAY_DEPARTURE",
    CASE WHEN YY.Dat_Depart     = TIMESTAMP '1900-01-01 00:00:01' THEN NULL ELSE YY.Dat_Depart     END AS "TRUCK_GATE_DEPARTURE",
    CASE WHEN YY.DATE_CNF       = TIMESTAMP '1900-01-01 00:00:01' THEN NULL ELSE YY.DATE_CNF       END AS "UDM_RECEIVING",
    CASE WHEN YY.DATE_PUT       = TIMESTAMP '1900-01-01 00:00:01' THEN NULL ELSE YY.DATE_PUT       END AS "UDM_POSITIONING",
    CASE WHEN YY.Appointment_Date = TIMESTAMP '1900-01-01 00:00:01' THEN NULL ELSE YY.Appointment_Date END AS "APPOINTMENT_DATE",
    YY.LASTUPDATE AS "UPDATED_DATE",
    '0' AS "ISDELETED"
  FROM ( 
    SELECT
      XX.INBOUNDREF AS INBOUNDREF,
      XX.ASN AS ASN,
      XX.DEPOT AS DEPOT,
      XX.ACTIVITY AS ACTIVITY,
      XX.ITEM AS ITEM, 
      MAX(XX.GRADE) AS GRADE, 
      XX.SUPPORT AS SUPPORT,
      SUM(CASE WHEN XX.QTYEXP IS NULL THEN 0 ELSE XX.QTYEXP END) AS QTY_EXPECT,
      SUM(CASE WHEN XX.QTYCNF IS NULL THEN 0 ELSE XX.QTYCNF END) AS QTY_CONFIRM,
      MAX(XX.DAT_CNF) AS DATE_CNF,
      MAX(XX.DAT_PUT) AS DATE_PUT,
      MAX(XX.LASTUPDATE) AS LASTUPDATE,
      MAX(XX.Dat_Gate ) AS Dat_Gate,
      MAX(XX.Dat_Dock_in) AS Dat_Dock_in,
      MAX(XX.Dat_Dock_out) AS Dat_Dock_out,
      MAX(XX.Dat_Depart) AS Dat_Depart,
      MAX(XX.DOCK) AS DOCK,
      MAX(XX.Lplate) AS Lplate,
      MAX(XX.Appointment_Date) AS Appointment_Date
    FROM (
      -- Expected Qty EDI
      SELECT 
        I22.I22NRC  AS INBOUNDREF, 
        I22.I22RFRC AS ASN, 
        I22.I22WHOU AS DEPOT,
        I22.I22CPNY AS ACTIVITY,
        I22.I22IDPA AS SUPPORT,
        I22.I22CITE AS ITEM, 
        NULL AS GRADE,
        SUM(I22.I22QTEX) AS QTYEXP,
        0 AS QTYCNF,
        TIMESTAMP '1900-01-01 00:00:01' AS DAT_CNF,
        TIMESTAMP '1900-01-01 00:00:01' AS DAT_PUT,
        TIMESTAMP '1900-01-01 00:00:01' AS Dat_Gate,
        TIMESTAMP '1900-01-01 00:00:01' AS Dat_Dock_in,
        TIMESTAMP '1900-01-01 00:00:01' AS Dat_Dock_out,
        TIMESTAMP '1900-01-01 00:00:01' AS Dat_Depart,
        TIMESTAMP '1900-01-01 00:00:01' AS Appointment_Date,
        NULL AS DOCK,
        NULL AS Lplate,
        MAX(GREATEST(
          COALESCE(I22.HVR_CHANGE_TIME, TIMESTAMP '1900-01-01 00:00:01'),
          COALESCE(I22.HVR_CHANGE_TIME, TIMESTAMP '1900-01-01 00:00:01')
        )) AS LASTUPDATE
      FROM MODELS.KERING_GLOBE.xprc03p I22
      WHERE I22WHOU = '001' AND I22CPNY = '100'
      GROUP BY I22.I22NRC, I22.I22RFRC, I22.I22WHOU, I22.I22CPNY, I22.I22IDPA, I22.I22CITE, I22.I22GREX 
      
      UNION ALL
      
      -- Received qty at IPG creation
      SELECT
        RE.RENBLF AS INBOUNDREF,
        RE.RERREC AS ASN,
        VG.VGCDPO AS DEPOT,
        VG.VGCACT AS ACTIVITY,
        VG.VGNSUP AS SUPPORT,
        VG.VGCART AS ITEM, 
        VG.VGCQAL AS GRADE,
        0 AS QTYEXP,
        SUM(VG.VGQMVG) AS QTYCNF,
        MAX(
          TO_TIMESTAMP( CASE WHEN RE.RETRVA = '0' THEN '1900-01-01 00:00:01' ELSE LPAD(RE.RESVAL, 2, '0') || LPAD(RE.REAVAL, 2, '0') ||'-'||LPAD(RE.REMVAL, 2, '0') ||'-'|| LPAD(RE.REJVAL, 2, '0') || ' '||
          SUBSTR(LPAD(RE.REHVAR,6,0),1,2)||':'|| SUBSTR(LPAD(RE.REHVAR,6,0),3,2)||':'|| SUBSTR(LPAD(RE.REHVAR,6,0),5,2) END ,'YYYY-MM-DD HH24:MI:SS' )
        ) AS DAT_CNF,
        MAX(CH.CHDAE9) AS DAT_PUT,
        (MIN(YMA.MOArrivalDate)) AS Dat_Gate,
        (MIN(YMB.MOBayDate))     AS Dat_Dock_in,
        (MIN(YMBE.MODepartureDate)) AS Dat_Dock_out,
        (MIN(YMD.MODepartureDate))  AS Dat_Depart,
        MAX(
          TO_TIMESTAMP( CASE WHEN RE.RESREC = 0 THEN '1900-01-01 00:00:01' ELSE LPAD(RE.RESREC, 2, '0') || LPAD(RE.REAREC, 2, '0') ||'-'||LPAD(RE.REMREC, 2, '0') ||'-'|| LPAD(RE.REJREC, 2, '0') || ' '||
          SUBSTR(LPAD(RE.REHREC,6,0),1,2)||':'|| SUBSTR(LPAD(RE.REHREC,6,0),3,2)||':'|| SUBSTR(LPAD(RE.REHREC,6,0),5,2) END,'YYYY-MM-DD HH24:MI:SS' )
        ) AS Appointment_Date,
        MIN(YMB.DOCK) AS DOCK,
        MIN(YMA.MOLICENCEPLATE1) AS Lplate,
        MAX(GREATEST(
          COALESCE(RE.HVR_CHANGE_TIME, TIMESTAMP '1900-01-01 00:00:01'),
          COALESCE(RE.HVR_CHANGE_TIME, TIMESTAMP '1900-01-01 00:00:01'),
          COALESCE(VG.HVR_CHANGE_TIME, TIMESTAMP '1900-01-01 00:00:01'),
          COALESCE(VG.HVR_CHANGE_TIME, TIMESTAMP '1900-01-01 00:00:01'),
          COALESCE(CH.HVR_CHANGE_TIME, TIMESTAMP '1900-01-01 00:00:01'),
          COALESCE(CH.HVR_CHANGE_TIME, TIMESTAMP '1900-01-01 00:00:01')
        )) AS LASTUPDATE
      FROM MODELS.KERING_GLOBE.hlrecpp RE
      INNER JOIN MODELS.KERING_GLOBE.hlmvtgp VG
        ON RE.RECDPO = VG.VGCDPO AND RE.RECACT = VG.VGCACT AND RE.RENANN = VG.VGNANN AND VG.VGNREC = RE.RENREC AND VG.VGCTVG = '100'
      LEFT JOIN MODELS.KERING_GLOBE.kbrechp CH
        ON CH.CHNANN = RE.RENANN AND RE.RENREC = CH.CHNREC AND VG.VGNSUP = CH.CHNUDM AND CH.CHNANF = RE.RENANN AND RE.RENREC = CH.CHNRFI
       AND CH.CHCDPO = RE.RECDPO AND CH.CHCACT = RE.RECACT 
      LEFT JOIN (
        SELECT UP.UPCACT, UP.UPNANN, UP.UPNREC, UP.UPCDPO,
               MAX(LPAD(COALESCE(U6.U6NARV,'0'), 2, '0') || LPAD(COALESCE(U6.U6NRDV,'0'), 9, '0')) AS APPOINTMENT_NR,
               MAX(U6.U6NARV) AS U6NARV,
               MAX(U6.U6NRDV) AS U6NRDV, 
               MAX(U6.U6CTMR) AS CARRIER,
               MAX(U6.U6LRDV) AS U6LRDV
        FROM MODELS.KERING_GLOBE.HLRDVRP UP 
        LEFT JOIN MODELS.KERING_GLOBE.HLRDVTP U6
          ON U6.U6CDPO = UP.UPCDPO AND UP.UPNARV = U6.U6NARV AND UP.UPNRDV = U6.U6NRDV
        GROUP BY UP.UPCACT, UP.UPNANN, UP.UPNREC, UP.UPCDPO
      ) U6A ON RE.RECACT = U6A.UPCACT AND RE.RENANN = U6A.UPNANN AND RE.RENREC = U6A.UPNREC AND RE.RECDPO = U6A.UPCDPO 
      LEFT JOIN (
        SELECT YM1.IDSite, YM1.IDDepot, YM1.MOState, YM1.MOAppointment,
               MIN(MOArrivalDate) AS MOArrivalDate , MAX(YM1.MOLICENCEPLATE1) AS MOLICENCEPLATE1
        FROM Historymovement YM1 
        WHERE YM1.IDSite = '1' AND YM1.IDDepot = '4' AND YM1.MOState = 20
        GROUP BY YM1.IDSite, YM1.IDDepot, YM1.MOState, YM1.MOAppointment
      ) YMA ON YMA.MOAppointment = U6A.U6LRDV 
      LEFT JOIN (
        SELECT YM2.IDSite, YM2.IDDepot, YM2.MOState, YM2.MOAppointment,
               MIN(YM2.HYTIMESTAMP) AS MOBayDate , MIN(d.DONAME) AS DOCK
        FROM Historymovement YM2 
        INNER JOIN DOCK d ON d.IDDOCK = YM2.IDDOCK 
        WHERE YM2.IDSite = '1' AND YM2.IDDepot = '4' AND YM2.MOState = 60 AND YM2.IDSTATUS = 3
        GROUP BY YM2.IDSite, YM2.IDDepot, YM2.MOState, YM2.MOAppointment
      ) YMB ON YMB.MOAppointment = U6A.U6LRDV 
      LEFT JOIN (
        SELECT YM4.IDSite, YM4.IDDepot, YM4.MOState, YM4.MOAppointment,
               MIN(HYTIMESTAMP) AS MODEPARTUREDATE , MIN(d.DONAME) AS DOCK
        FROM Historymovement YM4 
        INNER JOIN DOCK d ON d.IDDOCK = YM4.IDDOCK 
        WHERE YM4.IDSite = '1' AND YM4.IDDepot = '4' AND YM4.MOState = 60 AND YM4.IDSTATUS = 11
        GROUP BY YM4.IDSite, YM4.IDDepot, YM4.MOState, YM4.MOAppointment
      ) YMBE ON YMBE.MOAppointment = U6A.U6LRDV 
      LEFT JOIN (
        SELECT YM3.IDSite, YM3.IDDepot, YM3.MOState, YM3.MOAppointment,
               MIN(YM3.MODEPARTUREDATE) AS MODepartureDate
        FROM Historymovement YM3 
        WHERE YM3.IDSite = '1' AND YM3.IDDepot = '4' AND YM3.MOState = 99
        GROUP BY YM3.IDSite, YM3.IDDepot, YM3.MOState, YM3.MOAppointment
      ) YMD ON YMD.MOAppointment = U6A.U6LRDV 
      WHERE RE.RECACT = '100' AND RE.RECDPO = '001' AND RE.RESVAL <> 0
      GROUP BY RE.RENBLF, RE.RERREC, VG.VGCDPO, VG.VGCACT, VG.VGNSUP, VG.VGCART, VG.VGCQAL
    ) XX
    GROUP BY XX.INBOUNDREF, XX.ASN, XX.DEPOT, XX.ACTIVITY, XX.SUPPORT , XX.ITEM
  ) YY
  LEFT JOIN MODELS.KERING_GLOBE.KBCARTP CA
    ON CA.CACACT = YY.ACTIVITY AND CA.CASKUC = YY.ITEM
  LEFT JOIN (
    SELECT h1.*
    FROM MODELS.KERING_GLOBE.HLVLIDP h1
    INNER JOIN (
      SELECT MAX(VIACRE || LPAD(VIMCRE, 2, '0') || LPAD(VIJCRE, 2, '0') || LPAD(VIHCRE, 6, '0')) AS max_value, VICART
      FROM MODELS.KERING_GLOBE.HLVLIDP
      WHERE VICTYI = 'EAN13'
      GROUP BY VICART
    ) h2
      ON (h1.VIACRE || LPAD(h1.VIMCRE, 2, '0') || LPAD(h1.VIJCRE, 2, '0') || LPAD(h1.VIHCRE, 6, '0')) = h2.max_value
     AND h1.VICART = h2.VICART
    WHERE h1.VICTYI = 'EAN13'
  ) VI2 ON VI2.VICACT = CA.CACACT AND VI2.VICART = CA.CASKUC
),
/* Chunk 30: dev_filters — optional filters for test runs */
dev_filters AS (
  SELECT s.*
  FROM source_select s, params p, base_time_gate bt
  WHERE 1=1
    AND (p.FILTER_SKU               IS NULL OR s.SKU               = p.FILTER_SKU)
    AND (p.FILTER_INBOUND_REFERENCE IS NULL OR s.INBOUND_REFERENCE = p.FILTER_INBOUND_REFERENCE)
    AND (p.FILTER_ASN               IS NULL OR s.ASN               = p.FILTER_ASN)
    AND (p.FILTER_DOCK              IS NULL OR s.DOCK              = p.FILTER_DOCK)
    AND s.UPDATED_DATE >= bt.cutoff_ts
) SELECT * FROM dev_filters;


SELECT * FROM CRT_KER_01_INBOUND;

