CREATE OR REPLACE VIEW CRT_KER_05_MASTERITEM AS

WITH KBCARTP AS (
  SELECT CACACT, CASKUC, CASTNO, CALMOD, CAPART, CACOLC, CASIZC, CADROP, 
         CAPRCA, CAPRFA, CADEGR, CASUDE, CASCLA, CAMATN, CADESC, CABRDC, 
         CAHFFG, CATCIT, CAIHAM, CAICAL, CAPWGH, CAWTUM, CAPHGH, CAPWID, 
         CAPDPT, CAPVOL, CAVUOM, CADCUB, CATRCU, CAFTOO, CAFBOT, CAFHOR, 
         CAFVER, CAFTOP, CAPCOM, CAPOUC, CASTAC, CAFOWI, CAFOLD, CAFRAG, CADMAJ
  FROM MODELS.KERING_GLOBE.KBCARTP
),

LATEST_EAN AS (
  SELECT *
  FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY VICART ORDER BY VIACRE DESC, VIMCRE DESC, VIJCRE DESC, VIHCRE DESC) AS RN
    FROM MODELS.KERING_GLOBE.HLVLIDP
    WHERE VICTYI = 'EAN13' AND VICIVL != '3617132449729'
  )
  WHERE RN = 1
),

OBJECT_TS AS (
  SELECT DATEADD(hour, -4, LAST_UPDATE) AS MIN_TS
  FROM OBJECT_RUN
  WHERE OBJECT = '05_ITEMMASTERDATA'
)

SELECT  
  UPPER(HEX_ENCODE(MD5_BINARY('B-' || CA.CASKUC))) AS PK_FACT_ITEMMASTERDATA,
  'Reflex WEB B' AS ENVIRONMENT,
  CA.CASKUC AS SKU,
  CA.CASTNO AS SKU_TYPE,
  VI.VICIVL AS EAN,
  CA.CALMOD AS MODEL,
  CA.CAPART AS PART,
  CA.CACOLC AS COLOUR,
  CA.CASIZC AS SIZE,
  CA.CADROP AS "DROP",
  CA.CAPRCA AS PRODUCT_CATEGORY,
  CA.CAPRFA AS PRODUCT_SUBCATEGORY,
  CA.CADEGR AS TECHNICAL_CLASS,
  CA.CASUDE AS TECHNICAL_SUBCLASS,
  CA.CASCLA AS ARTICLE_SUBCLASS,
  CA.CAMATN AS STYLE_MATERIAL_VARIANT,
  CA.CADESC AS ITEM_DESCRIPTION,
  CA.CABRDC AS BRAND,
  CA.CAHFFG AS HANG_FLAT_FLAG,
  CA.CATCIT AS CITES_FLAG,
  CA.CAIHAM AS DANGEROUS_FLAG,
  CA.CAICAL AS ALCOHOL_FLAG,
  CA.CAPWGH AS PIECE_WEIGHT,
  CA.CAWTUM AS WEIGHT_UOM,
  CA.CAPHGH AS PIECE_HEIGHT,
  CA.CAPWID AS PIECE_WIDTH,
  CA.CAPDPT AS PIECE_DEPTH,
  CA.CAPVOL AS PIECE_VOLUME,
  CA.CAVUOM AS VOLUME_UOM,
  (CA.CAPHGH * CA.CAPWID * CA.CAPDPT) / 1000 AS CALCULATED_VOLUME,
  CA.CADCUB AS MEASUREMENT_DATE,
  CASE 
    WHEN CA.CATRCU = '1' THEN 'Cubiscan'
    WHEN CA.CAPVOL = 0 THEN 'Not Measured'
    ELSE 'Manual'
  END AS MEASUREMENT_MODE,
  VL.VLCFAS AS STORAGE_FAMILY,
  CA.CAFTOO AS ONLY_ON_THE_TOP_FLAG,
  CA.CAFBOT AS AT_THE_BOTTOM_ONLY_FLAG,
  CA.CAFHOR AS HORIZONTALLY_FLAG,
  CA.CAFVER AS VERTICALLY_FLAG,
  CA.CAFTOP AS ON_TOP_FLAG,
  CA.CAPCOM AS PERCENTAGE_COMPRESSION,
  CA.CAPOUC AS POUCHABLE_FLAG,
  CA.CASTAC AS STACKABLE_FLAG,
  CA.CAFOWI AS FOLDING_IN_THE_WIDTH_FLAG,
  CA.CAFOLD AS FOLDING_FLAG,
  CA.CAFRAG AS FRAGILE_FLAG,

  GREATEST(
    COALESCE(CA.CADMAJ, TO_TIMESTAMP('1900-01-01 00:00:00')),
    COALESCE(TRY_TO_TIMESTAMP(LPAD(AR.ARSMAJ, 2, '0') || LPAD(AR.ARAMAJ, 2, '0') || LPAD(AR.ARMMAJ, 2, '0') || LPAD(AR.ARJMAJ, 2, '0') || LPAD(AR.ARHMAJ, 6, '0')), TO_TIMESTAMP('1900-01-01 00:00:00')),
    COALESCE(TRY_TO_TIMESTAMP(LPAD(VL.VLSMAJ, 2, '0') || LPAD(VL.VLAMAJ, 2, '0') || LPAD(VL.VLMMAJ, 2, '0') || LPAD(VL.VLJMAJ, 2, '0') || LPAD(VL.VLHMAJ, 6, '0')), TO_TIMESTAMP('1900-01-01 00:00:00')),
    COALESCE(TRY_TO_TIMESTAMP(LPAD(VI.VISMAJ, 2, '0') || LPAD(VI.VIAMAJ, 2, '0') || LPAD(VI.VIMMAJ, 2, '0') || LPAD(VI.VIJMAJ, 2, '0') || LPAD(VI.VIHMAJ, 6, '0')), TO_TIMESTAMP('1900-01-01 00:00:00'))
  ) AS UPDATED_DATE,

  '0' AS ISDELETED

FROM KBCARTP CA
LEFT JOIN MODELS.KERING_GLOBE.HLARTIP AR 
  ON CA.CACACT = AR.ARCACT AND CA.CASKUC = AR.ARCART
LEFT JOIN MODELS.KERING_GLOBE.HLARVLP VL 
  ON CA.CACACT = VL.VLCACT AND CA.CASKUC = VL.VLCART AND VL.VLCVLA = '03'
LEFT JOIN LATEST_EAN VI 
  ON VI.VICACT = CA.CACACT AND VI.VICART = CA.CASKUC
JOIN OBJECT_TS OT ON TRUE
WHERE GREATEST(
    COALESCE(CA.CADMAJ, TO_TIMESTAMP('1900-01-01 00:00:00')),
    COALESCE(TRY_TO_TIMESTAMP(LPAD(AR.ARSMAJ, 2, '0') || LPAD(AR.ARAMAJ, 2, '0') || LPAD(AR.ARMMAJ, 2, '0') || LPAD(AR.ARJMAJ, 2, '0') || LPAD(AR.ARHMAJ, 6, '0')), TO_TIMESTAMP('1900-01-01 00:00:00')),
    COALESCE(TRY_TO_TIMESTAMP(LPAD(VL.VLSMAJ, 2, '0') || LPAD(VL.VLAMAJ, 2, '0') || LPAD(VL.VLMMAJ, 2, '0') || LPAD(VL.VLJMAJ, 2, '0') || LPAD(VL.VLHMAJ, 6, '0')), TO_TIMESTAMP('1900-01-01 00:00:00')),
    COALESCE(TRY_TO_TIMESTAMP(LPAD(VI.VISMAJ, 2, '0') || LPAD(VI.VIAMAJ, 2, '0') || LPAD(VI.VIMMAJ, 2, '0') || LPAD(VI.VIJMAJ, 2, '0') || LPAD(VI.VIHMAJ, 6, '0')), TO_TIMESTAMP('1900-01-01 00:00:00'))
  ) >= OT.MIN_TS;

  -- SELECT COUNT(*) FROM FACT_KER_05_MASTERITEM;
  SELECT * FROM USER_MANAGED.KERING_GLOBE_USER_MODELS.OBJECT_RUN; -- WHERE OBJECT = '05_ITEMMASTERDATA';
  INSERT INTO USER_MANAGED.KERING_GLOBE_USER_MODELS.OBJECT_RUN VALUES(100, 'GG_KERI_PRD',	'05_ITEMMASTERDATA',	'2020-01-01 06:21:31.228', null,'2000-01-01 00:00:00.000' );

  
