CREATE OR REPLACE PROCEDURE SMART_BI.BILLING_VAS_LOAD(SAFETY_HOURS INTEGER DEFAULT 4)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO FACT_BILLING_VAS t
  USING (
    SELECT *
    FROM   MODELS.KERING_GLOBE.CRT_BILLING_VAS  -- Updated view name
    WHERE  UPDATED_TS >= DATEADD(
             hour, - :SAFETY_HOURS,
             COALESCE(
               (SELECT LAST_UPDATE FROM SMART_BI.OBJECT_RUN WHERE "OBJECT" = 'BILLING_VAS'),  -- Updated object name
               TO_TIMESTAMP_NTZ('1900-01-01 00:00:00')
             )
           )
    -- Optional ad-hoc filters (uncomment as needed):
    -- AND SAP_ORDERID = '4500000000'
    -- AND VAS_CODE = 'ABC1234'
  ) s
  ON (
       t.P1CDPO   = s.P1CDPO
   AND t.P1CACT   = s.P1CACT
   AND t.P1NANP   = s.P1NANP
   AND t.P1NPRE   = s.P1NPRE
   AND t.VAS_CODE = s.VAS_CODE
  )

  WHEN MATCHED THEN UPDATE SET
      VERSION              = s.VERSION,
      QUANTITY_PRE         = s.QUANTITY_PRE,
      QUANTITY_FIX         = s.QUANTITY_FIX,
      ACTIVITY_DATE        = s.ACTIVITY_DATE,
      PREPARATION_CHILD    = s.PREPARATION_CHILD,
      PREPARATION_MOTHER   = s.PREPARATION_MOTHER,
      SAP_ORDERID          = s.SAP_ORDERID,
      VAS_CLUSTER          = s.VAS_CLUSTER,
      BRAND                = s.BRAND,
      OWNER                = s.OWNER,
      GRADE                = s.GRADE,
      UPDATED_TS           = s.UPDATED_TS

  WHEN NOT MATCHED THEN INSERT (
      P1CDPO, P1CACT, P1NANP, P1NPRE, VAS_CODE,
      VERSION, QUANTITY_PRE, QUANTITY_FIX, ACTIVITY_DATE, PREPARATION_CHILD, PREPARATION_MOTHER,
      SAP_ORDERID, VAS_CLUSTER, BRAND, OWNER, GRADE, UPDATED_TS
  )
  VALUES (
      s.P1CDPO, s.P1CACT, s.P1NANP, s.P1NPRE, s.VAS_CODE,
      s.VERSION, s.QUANTITY_PRE, s.QUANTITY_FIX, s.ACTIVITY_DATE, s.PREPARATION_CHILD, s.PREPARATION_MOTHER,
      s.SAP_ORDERID, s.VAS_CLUSTER, s.BRAND, s.OWNER, s.GRADE, s.UPDATED_TS
  );

  MERGE INTO SMART_BI.OBJECT_RUN d
  USING (
    SELECT 'BILLING_VAS' AS OBJECT,  -- Updated object name
           MAX(UPDATED_TS) AS LAST_UPDATE
    FROM   MODELS.KERING_GLOBE.CRT_BILLING_VAS
    WHERE  UPDATED_TS >= DATEADD(
             hour, - :SAFETY_HOURS,
             COALESCE(
               (SELECT LAST_UPDATE FROM SMART_BI.OBJECT_RUN WHERE "OBJECT" = 'BILLING_VAS'),
               TO_TIMESTAMP_NTZ('1900-01-01 00:00:00')
             )
           )
  ) s
  ON d."OBJECT" = s.OBJECT
  WHEN MATCHED THEN UPDATE
    SET d.LAST_UPDATE = GREATEST(COALESCE(d.LAST_UPDATE, s.LAST_UPDATE), s.LAST_UPDATE)
  WHEN NOT MATCHED THEN INSERT ("OBJECT", LAST_UPDATE)
    VALUES (s.OBJECT, s.LAST_UPDATE);

  RETURN 'BILLING_VAS_LOAD completed';
END;
$$;
