CREATE OR REPLACE VIEW MODELS.KERING_GLOBE.CRT_KER_04_STOCK AS
WITH
/*--------------------------------------------------------------
RANGE_PARAMS
- Set APPLY_RANGE = TRUE  → only rows where ge.HVR_CHANGE_TIME in [START_TS, END_TS)
- Set APPLY_RANGE = FALSE → ALL rows
--------------------------------------------------------------*/
RANGE_PARAMS AS (
  SELECT
    TRUE AS APPLY_RANGE,  -- flip to FALSE to disable the time window
    TO_TIMESTAMP_NTZ('2025-08-01 00:00:00') AS START_TS,
    TO_TIMESTAMP_NTZ('2025-08-31 23:59:59') AS END_TS
),

/*--------------------------------------------------------------
GE rows (stock status) with pushdown of the range filter
--------------------------------------------------------------*/
ge AS (
  SELECT *
  FROM MODELS.KERING_GLOBE.HLGEINP
  WHERE GECACT = '100'
    AND GECDPO = '001'
    AND GECTST IN ('200')
    AND (
      (SELECT APPLY_RANGE FROM RANGE_PARAMS) = FALSE
      OR (HVR_CHANGE_TIME >= (SELECT START_TS FROM RANGE_PARAMS)
      AND  HVR_CHANGE_TIME  < (SELECT END_TS   FROM RANGE_PARAMS))
    )
),

/* limit downstream scans to only relevant site/depot/receipt/color combos from GE */
ge_keys AS (
  SELECT DISTINCT
         GECACT, GECDPO, GENANN, GENREC, GENCOL
  FROM ge
),

/* inbound interface timestamps, scoped to GE receipts only */
inbound_interfaces AS (
  SELECT
      CHCDPO, CHCACT, CHNANN, CHNREC, CHNANF, CHNRFI,
      MIN(CHDET3) AS TK03_DATETIME,
      MAX(CHDET3) AS TK03_DATETIME2
  FROM MODELS.KERING_GLOBE.KBRECHP K
  JOIN ge_keys G
    ON G.GECACT = K.CHCACT
   AND G.GECDPO = K.CHCDPO
   AND G.GENANN = K.CHNANF
   AND G.GENREC = K.CHNRFI
  GROUP BY CHCDPO, CHCACT, CHNANN, CHNREC, CHNANF, CHNRFI
),

/* invoice presence (invoiced flag), scoped by GE site/depot/color */
inv AS (
  SELECT DISTINCT
      y.SHRDOR, p.PRCNPRE, p.PRCCDPO, p.PRCCACT, p.PRCNCOL, y.SHCINV
  FROM MODELS.KERING_GLOBE.HLPRCOP p
  JOIN MODELS.KERING_GLOBE.KBSHIPP y
    ON p.PRCCACT = y.SHCACT
   AND p.PRCCDPO = y.SHCDEP
   AND p.PRCNANN = y.SHNANN
   AND p.PRCNPRE = y.SHNPRP
  JOIN ge_keys g
    ON g.GECACT = y.SHCACT
   AND g.GECDPO = y.SHCDEP
   AND g.GENCOL = p.PRCNCOL
  WHERE y.SHCINV IS NOT NULL
),

/* latest EAN13 per SKU */
ean_latest AS (
  SELECT VICACT, VICART, VICIVL
  FROM (
    SELECT VICACT, VICART, VICIVL, VIACRE, VIMCRE, VIJCRE, VIHCRE,
           ROW_NUMBER() OVER (
             PARTITION BY VICART
             ORDER BY VIACRE DESC, VIMCRE DESC, VIJCRE DESC, VIHCRE DESC
           ) AS RN
    FROM MODELS.KERING_GLOBE.HLVLIDP
    WHERE VICTYI = 'EAN13'
  )
  WHERE RN = 1
)

SELECT
    'Reflex WEB B' AS ENVIRONMENT,
    su.SUNSUP AS UDM,
    ca.CASKUC AS SKU,
    ge.GECQAL AS QUALITY,
    em.EMC1EM || em.EMC2EM || em.EMC3EM || em.EMC4EM || em.EMC5EM AS LOCATION,
    ge.GEQGEI AS QUANTITY,
    ca.CASTNO AS SKU_TYPE,
    ge.GEACRE || '/' || ge.GEMCRE || '/' || ge.GEJCRE AS INBOUND_DATE,
    e.VICIVL AS EAN,
    ca.CALMOD AS MODEL, 
    ca.CAPART AS PART,
    ca.CACOLC AS COLOUR,
    ca.CASIZC AS SIZE,
    ca.CADROP AS "DROP",
    ca.CAPRCA AS PRODUCT_CATEGORY,
    ca.CAPRFA AS PRODUCT_SUBCATEGORY,
    ca.CADEGR AS TECHNICAL_CLASS,
    ca.CASUDE AS TECHNICAL_SUBCLASS,
    ca.CAMATN AS STYLE_MATERIAL_VARIANT,
    CASE WHEN ge.GENPRL = 0 THEN 'NO' ELSE 'YES' END AS OD_ASSOCIATED,
    ca.CADESC AS ITEM_DESCRIPTION,
    ca.CABRDC AS BRAND,
    re.RENBLF AS INBOUND_REFERENCE,
    re.RERREC AS ASN,
    'B' AS BUILDING,
    em.EMC1EM AS AISLE,
    CASE 
      WHEN em.EMNEMP IN (3874) THEN 'B1'
      WHEN em.EMNEMP IN (3875) THEN 'B2'
      ELSE TO_VARCHAR(em.EMC5EM)
    END AS BUILDING_PHYSICAL,
    em.EMCTYE AS LOCATION_TYPE,
    CASE 
      WHEN (ii.TK03_DATETIME IS NULL AND xp.O40TSTP IS NULL)
        OR inv.SHCINV IS NOT NULL 
        OR ge.GECQAL NOT IN ('1ST','QIN','TBR','PLO','EQI','RPL','ERP','2ND','SPL','E2P','PPL','EPL','E1P','FRE','FPL','SHO','OVE','DAM','DPL','EDP','FRC','BCN')
        OR ge.GECART NOT LIKE '8%'
        OR ge.GECPRP NOT IN ('AMG','AMF','AMM','BAG','BAF','BAM','BVG','BVF','BVM','GUG','GUF','GUM','SLG','SLF','SLM')
      THEN 'NOT_VISIBLE'
      WHEN ge.GECMBG IN ('PTW','RMQ') THEN 'VISIBLE_BLOCKED'
      ELSE 'VISIBLE'
    END AS SAP_VISIBILITY,
    CASE 
      WHEN em.EMC1EM LIKE '1S%' OR em.EMC1EM LIKE '2S%' OR em.EMC1EM LIKE '1T%' OR em.EMC1EM LIKE '2T%' OR em.EMC1EM LIKE '3T%' THEN 'SHELVES'
      WHEN em.EMC1EM LIKE '0R%' THEN 'RACKS'
      WHEN em.EMC1EM LIKE '1G%' OR em.EMC1EM LIKE '2G%' OR em.EMC1EM LIKE '3G%' OR em.EMC1EM LIKE '0G%' THEN 'GOH'
      WHEN em.EMNEMP = 3874 THEN 'DMS_STATIC'
      WHEN em.EMNEMP = 3875 THEN 'DMS_FLEX'
      WHEN em.EMC1EM LIKE '%CD' OR em.EMC1EM LIKE '%CS' THEN 'CONSIGNMENT'
      WHEN em.EMC1EM LIKE '0D%' THEN 'DANGEROUS'
      WHEN em.EMC1EM LIKE '1J%' OR em.EMC1EM LIKE '2J%' OR em.EMC1EM LIKE '3J%' OR em.EMC1EM LIKE '0J%' THEN 'JEWELRY'
      ELSE 'OTH'
    END AS STORAGE_AREA,
    LPAD(ge.GENANN::VARCHAR, 2, '0') || '/' || LPAD(ge.GENREC::VARCHAR, 9, '0') AS REFLEX_RECEIPT_ID,
    ge.GECPRP AS OWNER,
    CASE WHEN inv.SHCINV IS NULL THEN 0 ELSE 1 END AS INVOICED_FLAG,
    ca.CAHFFG AS HANG_FLAT_FLAG,
    ca.CATCIT AS CITES_FLAG,
    ca.CAIHAM AS DANGEROUS_FLAG,
    ca.CAICAL AS ALCOHOL_FLAG,
    ca.CAPWGH AS PIECE_WEIGHT,
    ca.CAWTUM AS WEIGHT_UOM,
    ca.CAPHGH AS PIECE_HEIGHT,
    ca.CAPWID AS PIECE_WIDTH,
    ca.CAPDPT AS PIECE_DEPTH,
    ca.CAPVOL AS PIECE_VOLUME,
    ca.CAVUOM AS VOLUME_UOM,
    ca.CAMDIN AS MADE_IN, 
    vl.VLCFAS AS STORAGE_FAMILY,
    vl.VLCFPR AS PREPARATION_FAMILY,
    ge.HVR_CHANGE_TIME AS UPDATED_DATE
FROM ge
JOIN MODELS.KERING_GLOBE.HLSUPPP   su ON ge.GENSUP = su.SUNSUP
JOIN MODELS.KERING_GLOBE.HLEMPLP   em ON su.SUNEMP = em.EMNEMP
JOIN MODELS.KERING_GLOBE.KBCARTP   ca ON ge.GECART = ca.CASKUC
LEFT JOIN MODELS.KERING_GLOBE.HLARVLP   vl ON ca.CACACT = vl.VLCACT AND ca.CASKUC = vl.VLCART AND vl.VLCVLA = '03'
LEFT JOIN MODELS.KERING_GLOBE.HLRECPP   re ON re.RECACT = ge.GECACT AND re.RENANN = ge.GENANN AND re.RENREC = ge.GENREC
LEFT JOIN inbound_interfaces             ii ON ii.CHCDPO = ge.GECDPO AND ii.CHCACT = ge.GECACT AND ii.CHNANF = ge.GENANN AND ii.CHNRFI = ge.GENREC
LEFT JOIN inv                            inv ON ge.GECACT = inv.PRCCACT AND ge.GECDPO = inv.PRCCDPO AND ge.GENCOL = inv.PRCNCOL
LEFT JOIN MODELS.KERING_GLOBE.XPSTOCP    xp ON xp.O40NGEI = ge.GENGEI
LEFT JOIN ean_latest                      e ON e.VICACT = ca.CACACT AND e.VICART = ca.CASKUC;
---------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_KER_04_STOCK_LOAD(SAFETY_HOURS INTEGER DEFAULT 4)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO FACT_KER_04_STOCK t
  USING (
    SELECT *
    FROM   MODELS.KERING_GLOBE.CRT_KER_04_STOCK
    WHERE  UPDATED_DATE >= DATEADD(
             hour, - :SAFETY_HOURS,
             COALESCE(
               (SELECT LAST_UPDATE FROM OBJECT_RUN WHERE "OBJECT" = 'CRT_KER_04_STOCK'),
               TO_TIMESTAMP_NTZ('1900-01-01 00:00:00')
             )
           )
  ) s
  ON (
       t.SKU      = s.SKU
   AND t.LOCATION = s.LOCATION
   AND t.QUALITY  = s.QUALITY
   AND t.OWNER    = s.OWNER
  )

  WHEN MATCHED THEN UPDATE SET
      t.ENVIRONMENT           = s.ENVIRONMENT,
      t.UDM                   = s.UDM,
      t.QUANTITY              = s.QUANTITY,
      t.SKU_TYPE              = s.SKU_TYPE,
      t.INBOUND_DATE          = s.INBOUND_DATE,
      t.EAN                   = s.EAN,
      t.MODEL                 = s.MODEL,
      t.PART                  = s.PART,
      t.COLOUR                = s.COLOUR,
      t.SIZE                  = s.SIZE,
      t."DROP"                = s."DROP",
      t.PRODUCT_CATEGORY      = s.PRODUCT_CATEGORY,
      t.PRODUCT_SUBCATEGORY   = s.PRODUCT_SUBCATEGORY,
      t.TECHNICAL_CLASS       = s.TECHNICAL_CLASS,
      t.TECHNICAL_SUBCLASS    = s.TECHNICAL_SUBCLASS,
      t.STYLE_MATERIAL_VARIANT= s.STYLE_MATERIAL_VARIANT,
      t.OD_ASSOCIATED         = s.OD_ASSOCIATED,
      t.ITEM_DESCRIPTION      = s.ITEM_DESCRIPTION,
      t.BRAND                 = s.BRAND,
      t.INBOUND_REFERENCE     = s.INBOUND_REFERENCE,
      t.ASN                   = s.ASN,
      t.BUILDING              = s.BUILDING,
      t.AISLE                 = s.AISLE,
      t.BUILDING_PHYSICAL     = s.BUILDING_PHYSICAL,
      t.LOCATION_TYPE         = s.LOCATION_TYPE,
      t.SAP_VISIBILITY        = s.SAP_VISIBILITY,
      t.STORAGE_AREA          = s.STORAGE_AREA,
      t.REFLEX_RECEIPT_ID     = s.REFLEX_RECEIPT_ID,
      t.INVOICED_FLAG         = s.INVOICED_FLAG,
      t.HANG_FLAT_FLAG        = s.HANG_FLAT_FLAG,
      t.CITES_FLAG            = s.CITES_FLAG,
      t.DANGEROUS_FLAG        = s.DANGEROUS_FLAG,
      t.ALCOHOL_FLAG          = s.ALCOHOL_FLAG,
      t.PIECE_WEIGHT          = s.PIECE_WEIGHT,
      t.WEIGHT_UOM            = s.WEIGHT_UOM,
      t.PIECE_HEIGHT          = s.PIECE_HEIGHT,
      t.PIECE_WIDTH           = s.PIECE_WIDTH,
      t.PIECE_DEPTH           = s.PIECE_DEPTH,
      t.PIECE_VOLUME          = s.PIECE_VOLUME,
      t.VOLUME_UOM            = s.VOLUME_UOM,
      t.MADE_IN               = s.MADE_IN,
      t.STORAGE_FAMILY        = s.STORAGE_FAMILY,
      t.PREPARATION_FAMILY    = s.PREPARATION_FAMILY,
      t.UPDATED_DATE          = s.UPDATED_DATE

  WHEN NOT MATCHED THEN INSERT (
      ENVIRONMENT, UDM, SKU, QUALITY, LOCATION, QUANTITY, SKU_TYPE, INBOUND_DATE, EAN, MODEL, PART,
      COLOUR, SIZE, "DROP", PRODUCT_CATEGORY, PRODUCT_SUBCATEGORY, TECHNICAL_CLASS, TECHNICAL_SUBCLASS,
      STYLE_MATERIAL_VARIANT, OD_ASSOCIATED, ITEM_DESCRIPTION, BRAND, INBOUND_REFERENCE, ASN, BUILDING,
      AISLE, BUILDING_PHYSICAL, LOCATION_TYPE, SAP_VISIBILITY, STORAGE_AREA, REFLEX_RECEIPT_ID, OWNER,
      INVOICED_FLAG, HANG_FLAT_FLAG, CITES_FLAG, DANGEROUS_FLAG, ALCOHOL_FLAG, PIECE_WEIGHT, WEIGHT_UOM,
      PIECE_HEIGHT, PIECE_WIDTH, PIECE_DEPTH, PIECE_VOLUME, VOLUME_UOM, MADE_IN, STORAGE_FAMILY,
      PREPARATION_FAMILY, UPDATED_DATE
  )
  VALUES (
      s.ENVIRONMENT, s.UDM, s.SKU, s.QUALITY, s.LOCATION, s.QUANTITY, s.SKU_TYPE, s.INBOUND_DATE, s.EAN, s.MODEL, s.PART,
      s.COLOUR, s.SIZE, s."DROP", s.PRODUCT_CATEGORY, s.PRODUCT_SUBCATEGORY, s.TECHNICAL_CLASS, s.TECHNICAL_SUBCLASS,
      s.STYLE_MATERIAL_VARIANT, s.OD_ASSOCIATED, s.ITEM_DESCRIPTION, s.BRAND, s.INBOUND_REFERENCE, s.ASN, s.BUILDING,
      s.AISLE, s.BUILDING_PHYSICAL, s.LOCATION_TYPE, s.SAP_VISIBILITY, s.STORAGE_AREA, s.REFLEX_RECEIPT_ID, s.OWNER,
      s.INVOICED_FLAG, s.HANG_FLAT_FLAG, s.CITES_FLAG, s.DANGEROUS_FLAG, s.ALCOHOL_FLAG, s.PIECE_WEIGHT, s.WEIGHT_UOM,
      s.PIECE_HEIGHT, s.PIECE_WIDTH, s.PIECE_DEPTH, s.PIECE_VOLUME, s.VOLUME_UOM, s.MADE_IN, s.STORAGE_FAMILY,
      s.PREPARATION_FAMILY, s.UPDATED_DATE
  );

  /* watermark */
  MERGE INTO OBJECT_RUN d
  USING (
    SELECT 'CRT_KER_04_STOCK' AS "OBJECT",
           MAX(UPDATED_DATE)   AS LAST_UPDATE
    FROM   MODELS.KERING_GLOBE.CRT_KER_04_STOCK
    WHERE  UPDATED_DATE >= DATEADD(
             hour, - :SAFETY_HOURS,
             COALESCE(
               (SELECT LAST_UPDATE FROM OBJECT_RUN WHERE "OBJECT" = 'CRT_KER_04_STOCK'),
               TO_TIMESTAMP_NTZ('1900-01-01 00:00:00')
             )
           )
  ) s
  ON d."OBJECT" = s."OBJECT"
  WHEN MATCHED THEN UPDATE SET d.LAST_UPDATE = GREATEST(COALESCE(d.LAST_UPDATE, s.LAST_UPDATE), s.LAST_UPDATE)
  WHEN NOT MATCHED THEN INSERT ("OBJECT", LAST_UPDATE) VALUES (s."OBJECT", s.LAST_UPDATE);

  RETURN 'SP_KER_04_STOCK_LOAD completed';
END;
$$;
