CREATE OR REPLACE VIEW MODELS.KERING_GLOBE.CRT_KER_04_STOCK AS
WITH
/*--------------------------------------------------------------
RANGE_PARAMS
- Set APPLY_RANGE = TRUE  → only rows where ge.HVR_CHANGE_TIME in [START_TS, END_TS)
- Set APPLY_RANGE = FALSE → ALL rows
--------------------------------------------------------------*/
RANGE_PARAMS AS (
  SELECT
    TRUE AS APPLY_RANGE,  -- flip to FALSE to disable the time window
    TO_TIMESTAMP_NTZ('2025-08-01 00:00:00') AS START_TS,
    TO_TIMESTAMP_NTZ('2025-08-31 23:59:59') AS END_TS
),

/*--------------------------------------------------------------
GE rows (stock status) with pushdown of the range filter
--------------------------------------------------------------*/
ge AS (
  SELECT *
  FROM MODELS.KERING_GLOBE.HLGEINP
  WHERE GECACT = '100'
    AND GECDPO = '001'
    AND GECTST IN ('200')
    AND (
      (SELECT APPLY_RANGE FROM RANGE_PARAMS) = FALSE
      OR (HVR_CHANGE_TIME >= (SELECT START_TS FROM RANGE_PARAMS)
      AND  HVR_CHANGE_TIME  < (SELECT END_TS   FROM RANGE_PARAMS))
    )
),

/* limit downstream scans to only relevant site/depot/receipt/color combos from GE */
ge_keys AS (
  SELECT DISTINCT
         GECACT, GECDPO, GENANN, GENREC, GENCOL
  FROM ge
),

/* inbound interface timestamps, scoped to GE receipts only */
inbound_interfaces AS (
  SELECT
      CHCDPO, CHCACT, CHNANN, CHNREC, CHNANF, CHNRFI,
      MIN(CHDET3) AS TK03_DATETIME,
      MAX(CHDET3) AS TK03_DATETIME2
  FROM MODELS.KERING_GLOBE.KBRECHP K
  JOIN ge_keys G
    ON G.GECACT = K.CHCACT
   AND G.GECDPO = K.CHCDPO
   AND G.GENANN = K.CHNANF
   AND G.GENREC = K.CHNRFI
  GROUP BY CHCDPO, CHCACT, CHNANN, CHNREC, CHNANF, CHNRFI
),

/* invoice presence (invoiced flag), scoped by GE site/depot/color */
inv AS (
  SELECT DISTINCT
      y.SHRDOR, p.PRCNPRE, p.PRCCDPO, p.PRCCACT, p.PRCNCOL, y.SHCINV
  FROM MODELS.KERING_GLOBE.HLPRCOP p
  JOIN MODELS.KERING_GLOBE.KBSHIPP y
    ON p.PRCCACT = y.SHCACT
   AND p.PRCCDPO = y.SHCDEP
   AND p.PRCNANN = y.SHNANN
   AND p.PRCNPRE = y.SHNPRP
  JOIN ge_keys g
    ON g.GECACT = y.SHCACT
   AND g.GECDPO = y.SHCDEP
   AND g.GENCOL = p.PRCNCOL
  WHERE y.SHCINV IS NOT NULL
),

/* latest EAN13 per SKU */
ean_latest AS (
  SELECT VICACT, VICART, VICIVL
  FROM (
    SELECT VICACT, VICART, VICIVL, VIACRE, VIMCRE, VIJCRE, VIHCRE,
           ROW_NUMBER() OVER (
             PARTITION BY VICART
             ORDER BY VIACRE DESC, VIMCRE DESC, VIJCRE DESC, VIHCRE DESC
           ) AS RN
    FROM MODELS.KERING_GLOBE.HLVLIDP
    WHERE VICTYI = 'EAN13'
  )
  WHERE RN = 1
)

SELECT
    'Reflex WEB B' AS ENVIRONMENT,
    su.SUNSUP AS UDM,
    ca.CASKUC AS SKU,
    ge.GECQAL AS QUALITY,
    em.EMC1EM || em.EMC2EM || em.EMC3EM || em.EMC4EM || em.EMC5EM AS LOCATION,
    ge.GEQGEI AS QUANTITY,
    ca.CASTNO AS SKU_TYPE,
    ge.GEACRE || '/' || ge.GEMCRE || '/' || ge.GEJCRE AS INBOUND_DATE,
    e.VICIVL AS EAN,
    ca.CALMOD AS MODEL, 
    ca.CAPART AS PART,
    ca.CACOLC AS COLOUR,
    ca.CASIZC AS SIZE,
    ca.CADROP AS "DROP",
    ca.CAPRCA AS PRODUCT_CATEGORY,
    ca.CAPRFA AS PRODUCT_SUBCATEGORY,
    ca.CADEGR AS TECHNICAL_CLASS,
    ca.CASUDE AS TECHNICAL_SUBCLASS,
    ca.CAMATN AS STYLE_MATERIAL_VARIANT,
    CASE WHEN ge.GENPRL = 0 THEN 'NO' ELSE 'YES' END AS OD_ASSOCIATED,
    ca.CADESC AS ITEM_DESCRIPTION,
    ca.CABRDC AS BRAND,
    re.RENBLF AS INBOUND_REFERENCE,
    re.RERREC AS ASN,
    'B' AS BUILDING,
    em.EMC1EM AS AISLE,
    CASE 
      WHEN em.EMNEMP IN (3874) THEN 'B1'
      WHEN em.EMNEMP IN (3875) THEN 'B2'
      ELSE TO_VARCHAR(em.EMC5EM)
    END AS BUILDING_PHYSICAL,
    em.EMCTYE AS LOCATION_TYPE,
    CASE 
      WHEN (ii.TK03_DATETIME IS NULL AND xp.O40TSTP IS NULL)
        OR inv.SHCINV IS NOT NULL 
        OR ge.GECQAL NOT IN ('1ST','QIN','TBR','PLO','EQI','RPL','ERP','2ND','SPL','E2P','PPL','EPL','E1P','FRE','FPL','SHO','OVE','DAM','DPL','EDP','FRC','BCN')
        OR ge.GECART NOT LIKE '8%'
        OR ge.GECPRP NOT IN ('AMG','AMF','AMM','BAG','BAF','BAM','BVG','BVF','BVM','GUG','GUF','GUM','SLG','SLF','SLM')
      THEN 'NOT_VISIBLE'
      WHEN ge.GECMBG IN ('PTW','RMQ') THEN 'VISIBLE_BLOCKED'
      ELSE 'VISIBLE'
    END AS SAP_VISIBILITY,
    CASE 
      WHEN em.EMC1EM LIKE '1S%' OR em.EMC1EM LIKE '2S%' OR em.EMC1EM LIKE '1T%' OR em.EMC1EM LIKE '2T%' OR em.EMC1EM LIKE '3T%' THEN 'SHELVES'
      WHEN em.EMC1EM LIKE '0R%' THEN 'RACKS'
      WHEN em.EMC1EM LIKE '1G%' OR em.EMC1EM LIKE '2G%' OR em.EMC1EM LIKE '3G%' OR em.EMC1EM LIKE '0G%' THEN 'GOH'
      WHEN em.EMNEMP = 3874 THEN 'DMS_STATIC'
      WHEN em.EMNEMP = 3875 THEN 'DMS_FLEX'
      WHEN em.EMC1EM LIKE '%CD' OR em.EMC1EM LIKE '%CS' THEN 'CONSIGNMENT'
      WHEN em.EMC1EM LIKE '0D%' THEN 'DANGEROUS'
      WHEN em.EMC1EM LIKE '1J%' OR em.EMC1EM LIKE '2J%' OR em.EMC1EM LIKE '3J%' OR em.EMC1EM LIKE '0J%' THEN 'JEWELRY'
      ELSE 'OTH'
    END AS STORAGE_AREA,
    LPAD(ge.GENANN::VARCHAR, 2, '0') || '/' || LPAD(ge.GENREC::VARCHAR, 9, '0') AS REFLEX_RECEIPT_ID,
    ge.GECPRP AS OWNER,
    CASE WHEN inv.SHCINV IS NULL THEN 0 ELSE 1 END AS INVOICED_FLAG,
    ca.CAHFFG AS HANG_FLAT_FLAG,
    ca.CATCIT AS CITES_FLAG,
    ca.CAIHAM AS DANGEROUS_FLAG,
    ca.CAICAL AS ALCOHOL_FLAG,
    ca.CAPWGH AS PIECE_WEIGHT,
    ca.CAWTUM AS WEIGHT_UOM,
    ca.CAPHGH AS PIECE_HEIGHT,
    ca.CAPWID AS PIECE_WIDTH,
    ca.CAPDPT AS PIECE_DEPTH,
    ca.CAPVOL AS PIECE_VOLUME,
    ca.CAVUOM AS VOLUME_UOM,
    ca.CAMDIN AS MADE_IN, 
    vl.VLCFAS AS STORAGE_FAMILY,
    vl.VLCFPR AS PREPARATION_FAMILY,
    ge.HVR_CHANGE_TIME AS UPDATED_DATE
FROM ge
JOIN MODELS.KERING_GLOBE.HLSUPPP   su ON ge.GENSUP = su.SUNSUP
JOIN MODELS.KERING_GLOBE.HLEMPLP   em ON su.SUNEMP = em.EMNEMP
JOIN MODELS.KERING_GLOBE.KBCARTP   ca ON ge.GECART = ca.CASKUC
LEFT JOIN MODELS.KERING_GLOBE.HLARVLP   vl ON ca.CACACT = vl.VLCACT AND ca.CASKUC = vl.VLCART AND vl.VLCVLA = '03'
LEFT JOIN MODELS.KERING_GLOBE.HLRECPP   re ON re.RECACT = ge.GECACT AND re.RENANN = ge.GENANN AND re.RENREC = ge.GENREC
LEFT JOIN inbound_interfaces             ii ON ii.CHCDPO = ge.GECDPO AND ii.CHCACT = ge.GECACT AND ii.CHNANF = ge.GENANN AND ii.CHNRFI = ge.GENREC
LEFT JOIN inv                            inv ON ge.GECACT = inv.PRCCACT AND ge.GECDPO = inv.PRCCDPO AND ge.GENCOL = inv.PRCNCOL
LEFT JOIN MODELS.KERING_GLOBE.XPSTOCP    xp ON xp.O40NGEI = ge.GENGEI
LEFT JOIN ean_latest                      e ON e.VICACT = ca.CACACT AND e.VICART = ca.CASKUC;
